/* ============================================================================
 * POLITISCAN · Registro de ideologías
 * ----------------------------------------------------------------------------
 * Script clásico (sin ES modules) para que index.html funcione también con
 * file://. Expone window.PS_IDEOLOGIES.
 *
 * Campos de cada entrada:
 *   id    identificador estable (no lo cambies: es la clave del progreso)
 *   n     nombre visible
 *   y     periodo histórico de referencia
 *   d     descripción breve (cara frontal de la tarjeta)
 *   t     tesis central / qué defiende
 *   c     crítica principal o límite conocido
 *   kw    palabras clave para el analizador local de respaldo (opcional)
 *   risk  0 democrática · 1 autoritaria de baja intensidad · 2 antidemocrática
 *         · 3 extremista => otorga PIN DE LA VERGÜENZA
 *   why   (solo risk 3) por qué fue destructiva. Es el texto del pin.
 * ==========================================================================*/
(function (global) {
  'use strict';

  var F = [
    /* ---------------------------------------------------------------- 01 */
    {
      id: 'liberalismo', n: 'Liberalismo', code: 'LIB',
      blurb: 'La libertad individual como eje: límites al poder, derechos y mercado.',
      items: [
        { id: 'lib-clasico', n: 'Liberalismo clásico', y: 's. XVII–XIX', d: 'Locke, Smith, Constant: derechos naturales, Estado mínimo y libertad de comercio.', t: 'El poder debe estar limitado por ley y por los derechos del individuo.', c: 'Ignoró durante un siglo que sin poder adquisitivo la libertad formal es hueca.', kw: ['libertad individual', 'estado mínimo', 'derechos naturales', 'libre comercio', 'propiedad privada'] },
        { id: 'lib-moderno', n: 'Liberalismo moderno', y: 's. XX', d: 'Keynes, Rawls, Beveridge: libertad real exige un suelo material garantizado.', t: 'El Estado corrige fallos de mercado y asegura igualdad de oportunidades.', c: 'Acusado de expandir la burocracia y de diluir la responsabilidad individual.', kw: ['igualdad de oportunidades', 'estado del bienestar', 'servicios públicos', 'redistribución moderada'] },
        { id: 'lib-neoliberalismo', n: 'Neoliberalismo', y: '1970–', d: 'Hayek, Friedman, Escuela de Chicago: desregulación, privatización, disciplina fiscal.', t: 'El mercado asigna mejor que cualquier planificador; el Estado debe replegarse.', c: 'Correlaciona con aumentos de desigualdad y con crisis financieras desreguladas.', kw: ['privatizar', 'desregular', 'bajar impuestos', 'recortar gasto público', 'competencia'] },
        { id: 'lib-ordoliberalismo', n: 'Ordoliberalismo', y: '1930–', d: 'Escuela de Friburgo: mercado libre pero con reglas fuertes fijadas por el Estado.', t: 'La competencia no es natural: hay que construirla y defenderla por ley.', c: 'Su ortodoxia de déficit cero agravó la austeridad europea post-2010.', kw: ['economía social de mercado', 'reglas fiscales', 'antimonopolio', 'estabilidad de precios'] },
        { id: 'lib-economico', n: 'Liberalismo económico', y: 's. XVIII–', d: 'Prioriza libertad de empresa, contratos y mercados abiertos.', t: 'La prosperidad nace del intercambio voluntario.', c: 'Poca respuesta a externalidades y a concentración de poder privado.', kw: ['libre mercado', 'emprender', 'menos trabas', 'apertura comercial'] },
        { id: 'lib-social', n: 'Liberalismo social', y: 's. XX', d: 'Hobhouse, Beveridge: derechos sociales como condición de la libertad.', t: 'Sanidad, educación y renta mínima habilitan al individuo.', c: 'Tensión permanente entre gasto y sostenibilidad fiscal.', kw: ['derechos sociales', 'sanidad universal', 'educación pública', 'renta mínima'] },
        { id: 'lib-cultural', n: 'Liberalismo cultural', y: 's. XX–', d: 'Máxima autonomía en costumbres, expresión y vida privada.', t: 'El Estado no legisla la moral privada.', c: 'Choca con comunidades que reclaman protección de sus normas propias.', kw: ['libertad de expresión', 'moral privada', 'derechos civiles', 'no censura'] },
        { id: 'lib-igualitario', n: 'Liberalismo igualitario', y: '1971–', d: 'Rawls: desigualdades solo justas si benefician a quien está peor.', t: 'Justicia como equidad tras el "velo de ignorancia".', c: 'Criticado por abstracto y por ignorar el poder real.', kw: ['justicia distributiva', 'velo de ignorancia', 'equidad'] },
        { id: 'lib-conservador', n: 'Liberalismo conservador', y: 's. XIX–', d: 'Libertad económica combinada con valores tradicionales y orden.', t: 'Mercado libre dentro de una sociedad moralmente estable.', c: 'Contradicción entre disolución de mercado y conservación de costumbres.', kw: ['libertad económica', 'orden', 'valores tradicionales', 'familia y mercado'] },
        { id: 'lib-progresista', n: 'Liberalismo progresista', y: 's. XX–', d: 'Reforma constante hacia mayor inclusión y derechos.', t: 'La libertad se amplía extendiéndola a quien fue excluido.', c: 'Riesgo de tecnocracia y de desconexión con las clases populares.', kw: ['inclusión', 'reformas', 'ampliar derechos', 'progreso'] },
        { id: 'lib-radical', n: 'Liberalismo radical', y: 's. XIX', d: 'Sufragio universal, anticlericalismo, república: el ala izquierda del liberalismo decimonónico.', t: 'Democratizar el liberalismo hasta el final.', c: 'Fragmentado; absorbido por socialdemocracia y liberalismo social.', kw: ['sufragio universal', 'república', 'anticlerical'] },
        { id: 'lib-nacional', n: 'Liberalismo nacional', y: 's. XIX', d: 'Une libertades constitucionales con construcción del Estado-nación.', t: 'Nación soberana y régimen liberal van juntos.', c: 'Sirvió de puente hacia nacionalismos excluyentes.', kw: ['unificación nacional', 'estado nación', 'soberanía liberal'] },
        { id: 'lib-verde', n: 'Liberalismo verde', y: '1990–', d: 'Instrumentos de mercado para resolver la crisis ecológica.', t: 'Precio al carbono, innovación y regulación inteligente.', c: 'Discutido si el ritmo de mercado alcanza la urgencia climática.', kw: ['precio al carbono', 'impuesto verde', 'mercado de emisiones', 'innovación limpia'] },
        { id: 'lib-libertario', n: 'Liberalismo libertario', y: 's. XX–', d: 'Frontera con el libertarismo: Estado reducido casi al mínimo.', t: 'Cuanta menos coerción estatal, mejor.', c: 'Subestima monopolios y bienes públicos.', kw: ['estado mínimo', 'no coerción', 'impuestos son robo'] },
        { id: 'lib-civico', n: 'Liberalismo cívico', y: 's. XX–', d: 'Ciudadanía activa, deberes cívicos y virtud pública.', t: 'La libertad requiere ciudadanos comprometidos, no solo consumidores.', c: 'Difícil de sostener en sociedades despolitizadas.', kw: ['ciudadanía', 'virtud cívica', 'participación'] },
        { id: 'lib-secular', n: 'Liberalismo secular', y: 's. XVIII–', d: 'Separación estricta Iglesia-Estado y neutralidad religiosa.', t: 'Lo público no se rige por doctrina religiosa.', c: 'Debate sobre si la neutralidad es realmente neutral.', kw: ['laicidad', 'separación iglesia estado', 'estado laico'] },
        { id: 'lib-constitucional', n: 'Liberalismo constitucional', y: 's. XVIII–', d: 'Imperio de la ley, división de poderes, control judicial.', t: 'Las reglas del juego limitan incluso a la mayoría.', c: 'Puede convertir el poder judicial en actor político no electo.', kw: ['división de poderes', 'estado de derecho', 'constitución', 'contrapesos'] },
        { id: 'lib-democratico', n: 'Liberalismo democrático', y: 's. XIX–', d: 'Síntesis entre derechos individuales y soberanía popular.', t: 'Ni mayoría sin límites ni derechos sin votos.', c: 'Tensión estructural mayoría/minoría nunca resuelta.', kw: ['democracia liberal', 'derechos y votos', 'pluralismo'] },
        { id: 'lib-humanista', n: 'Liberalismo humanista', y: 's. XX–', d: 'Dignidad de la persona como fundamento último.', t: 'Las instituciones existen para el florecimiento humano.', c: 'Principios amplios, políticas concretas ambiguas.', kw: ['dignidad humana', 'derechos humanos', 'humanismo'] },
        { id: 'lib-paleoliberalismo', n: 'Paleoliberalismo', y: 's. XX–', d: 'Retorno purista al liberalismo previo al Estado del bienestar.', t: 'El siglo XX desvirtuó el liberalismo original.', c: 'Nostalgia de un mundo con sufragio censitario y sin red de protección.', kw: ['liberalismo original', 'antes del bienestar', 'patrón oro'] }
      ]
    },
    /* ---------------------------------------------------------------- 02 */
    {
      id: 'conservadurismo', n: 'Conservadurismo', code: 'CON',
      blurb: 'Prudencia ante el cambio: instituciones heredadas, orden y continuidad.',
      items: [
        { id: 'con-clasico', n: 'Conservadurismo clásico', y: '1790–', d: 'Burke: la sociedad es un contrato entre generaciones, no un plano de ingeniería.', t: 'Reformar sí, refundar no.', c: 'Puede blindar injusticias solo porque son antiguas.', kw: ['tradición', 'reforma gradual', 'prudencia', 'herencia'] },
        { id: 'con-liberal', n: 'Conservadurismo liberal', y: 's. XIX–', d: 'Libertad de mercado sobre bases institucionales estables.', t: 'Capitalismo con orden y ley.', c: 'Sus dos mitades tiran en direcciones opuestas.', kw: ['mercado y orden', 'centroderecha', 'estabilidad institucional'] },
        { id: 'con-nacional', n: 'Conservadurismo nacional', y: 's. XX–', d: 'Soberanía, control migratorio e identidad nacional como prioridad.', t: 'La nación es la comunidad política real.', c: 'Frontera porosa con el nacionalismo excluyente.', kw: ['soberanía nacional', 'control de fronteras', 'identidad nacional'], risk: 1 },
        { id: 'con-social', n: 'Conservadurismo social', y: 's. XIX–', d: 'Protección estatal a familias y trabajadores dentro de un orden moral.', t: 'Cohesión social por encima del laissez-faire.', c: 'Paternalismo sobre las decisiones privadas.', kw: ['familia', 'cohesión social', 'protección al trabajador'] },
        { id: 'con-religioso', n: 'Conservadurismo religioso', y: 's. XIX–', d: 'La fe como fuente de legitimidad de las normas públicas.', t: 'La moral revelada debe orientar la ley.', c: 'Colisiona con la libertad de conciencia de los no creyentes.', kw: ['valores religiosos', 'moral cristiana', 'ley divina'] },
        { id: 'con-fiscal', n: 'Conservadurismo fiscal', y: 's. XX–', d: 'Déficit bajo, deuda controlada, gasto contenido.', t: 'Endeudarse es hipotecar a la próxima generación.', c: 'La austeridad procíclica agrava las recesiones.', kw: ['déficit cero', 'reducir deuda', 'austeridad', 'equilibrio presupuestario'] },
        { id: 'con-paternalista', n: 'Conservadurismo paternalista', y: '1840–', d: 'Disraeli, "One Nation": las élites tienen deberes hacia los de abajo.', t: 'Obligación moral de proteger al débil para evitar la revuelta.', c: 'Caridad desde arriba en lugar de derechos.', kw: ['one nation', 'deber de las élites', 'paternalismo'] },
        { id: 'con-neoconservadurismo', n: 'Neoconservadurismo', y: '1970–', d: 'Intervencionismo exterior para exportar democracia y contener rivales.', t: 'El poder militar sostiene el orden liberal.', c: 'Irak 2003: coste humano enorme y premisas falsas.', kw: ['intervención militar', 'exportar democracia', 'hegemonía', 'guerra preventiva'], risk: 1 },
        { id: 'con-paleoconservadurismo', n: 'Paleoconservadurismo', y: '1980–', d: 'Aislacionismo, tradición local y rechazo al globalismo.', t: 'Primero la comunidad propia; fuera del mundo, nada que ganar.', c: 'Deriva frecuente hacia el nativismo.', kw: ['aislacionismo', 'antiglobalismo', 'tradición local'], risk: 1 },
        { id: 'con-tradicionalista', n: 'Tradicionalismo', y: 's. XIX–', d: 'Orden trascendente previo a la modernidad; rechazo de la Ilustración.', t: 'La verdad no se vota: se hereda.', c: 'Incompatible con el pluralismo democrático.', kw: ['orden trascendente', 'antimoderno', 'contrarrevolución'], risk: 1 },
        { id: 'con-comunitario', n: 'Conservadurismo comunitario', y: '1980–', d: 'La comunidad, no el individuo aislado, produce sentido y virtud.', t: 'Somos seres situados en vínculos concretos.', c: 'Puede legitimar la presión del grupo sobre el disidente.', kw: ['comunidad', 'vínculos', 'arraigo', 'vecindad'] },
        { id: 'con-cristiano', n: 'Conservadurismo cristiano', y: 's. XIX–', d: 'Doctrina social cristiana aplicada a familia, trabajo y solidaridad.', t: 'Dignidad, subsidiariedad y bien común.', c: 'Selectividad al aplicar la doctrina según conveniencia política.', kw: ['doctrina social', 'subsidiariedad', 'bien común'] },
        { id: 'con-monarquico', n: 'Conservadurismo monárquico', y: 's. XVIII–', d: 'La corona como símbolo de continuidad y neutralidad institucional.', t: 'Un jefe de Estado fuera de la disputa partidista.', c: 'Cargo hereditario sin legitimidad electoral.', kw: ['monarquía', 'corona', 'continuidad dinástica'] },
        { id: 'con-autoritario', n: 'Conservadurismo autoritario', y: 's. XX', d: 'Orden por encima de libertades; tolera la suspensión de derechos.', t: 'Sin autoridad fuerte no hay sociedad estable.', c: 'Ha justificado dictaduras y represión sistemática.', kw: ['mano dura', 'orden ante todo', 'suspender derechos', 'estado de excepción'], risk: 2 },
        { id: 'con-constitucional', n: 'Conservadurismo constitucional', y: 's. XX–', d: 'Defensa literal del texto constitucional frente a reinterpretaciones.', t: 'Las reglas escritas contienen a los gobernantes.', c: 'Congela el derecho en el contexto de quien lo escribió.', kw: ['originalismo', 'letra de la constitución', 'no reinterpretar'] },
        { id: 'con-verde', n: 'Conservadurismo verde', y: '1990–', d: 'Conservar el paisaje y el patrimonio natural como herencia.', t: 'Ecología es, literalmente, conservación.', c: 'Poca ambición ante la escala del problema climático.', kw: ['conservar el paisaje', 'patrimonio natural', 'ecología conservadora'] }
      ]
    },
    /* ---------------------------------------------------------------- 03 */
    {
      id: 'socialismo', n: 'Socialismo', code: 'SOC',
      blurb: 'Propiedad social, igualdad material y control democrático de la economía.',
      items: [
        { id: 'soc-democratico', n: 'Socialismo democrático', y: 's. XX–', d: 'Transformación socialista dentro de las reglas democráticas.', t: 'Sin democracia no hay socialismo.', c: 'Los límites del poder económico privado frenan sus programas.', kw: ['socialismo democrático', 'nacionalizar con votos', 'democracia económica'] },
        { id: 'soc-revolucionario', n: 'Socialismo revolucionario', y: 's. XIX–', d: 'Ruptura con el orden burgués mediante acción de masas.', t: 'Las clases dominantes no ceden por persuasión.', c: 'Históricamente derivó en dictaduras de partido.', kw: ['revolución', 'insurrección', 'derrocar el sistema'], risk: 1 },
        { id: 'soc-utopico', n: 'Socialismo utópico', y: '1800–1848', d: 'Owen, Fourier, Saint-Simon: comunidades modelo como semilla del cambio.', t: 'El ejemplo convence más que la lucha.', c: 'Casi todos los experimentos fracasaron económicamente.', kw: ['comunidad modelo', 'falansterio', 'cooperativa utópica'] },
        { id: 'soc-cientifico', n: 'Socialismo científico', y: '1848–', d: 'Marx y Engels: análisis materialista de la historia y del capital.', t: 'El capitalismo genera sus propias contradicciones.', c: 'Predicciones sobre el colapso inminente no se cumplieron.', kw: ['materialismo histórico', 'plusvalía', 'lucha de clases'] },
        { id: 'soc-libertario', n: 'Socialismo libertario', y: 's. XIX–', d: 'Socialismo sin Estado: autogestión y federación libre.', t: 'Propiedad común sin aparato burocrático.', c: 'Escasa evidencia de viabilidad a gran escala.', kw: ['autogestión', 'sin estado', 'federación libre'] },
        { id: 'soc-cristiano', n: 'Socialismo cristiano', y: 's. XIX–', d: 'Evangelio leído como mandato de justicia social.', t: 'La opción por los pobres como programa político.', c: 'Tensión con las jerarquías eclesiásticas.', kw: ['evangelio y justicia', 'opción por los pobres', 'teología de la liberación'] },
        { id: 'soc-arabe', n: 'Socialismo árabe', y: '1950–1970', d: 'Nasserismo y baazismo: panarabismo, nacionalizaciones y Estado desarrollista.', t: 'Independencia económica frente al colonialismo.', c: 'Derivó en regímenes de partido único y culto al líder.', kw: ['nasserismo', 'baazismo', 'panarabismo'], risk: 1 },
        { id: 'soc-africano', n: 'Socialismo africano', y: '1960–1980', d: 'Nyerere (ujamaa), Senghor: comunitarismo tradicional como base socialista.', t: 'África no necesita copiar ni a Moscú ni a Washington.', c: 'La colectivización forzada en Tanzania hundió la producción agrícola.', kw: ['ujamaa', 'comunitarismo africano', 'no alineados'] },
        { id: 'soc-mercado', n: 'Socialismo de mercado', y: 's. XX–', d: 'Empresas de propiedad social compitiendo en mercados reales.', t: 'Mercados sí, capitalistas no.', c: 'Difícil disciplina financiera sin propietarios privados.', kw: ['empresas públicas competitivas', 'mercado socialista'] },
        { id: 'soc-autogestionario', n: 'Socialismo autogestionario', y: '1950–1990', d: 'Modelo yugoslavo: la empresa la dirigen sus trabajadores.', t: 'Quien produce, decide.', c: 'Subinversión crónica y desigualdad entre empresas.', kw: ['consejos obreros', 'empresa autogestionada', 'cogestión'] },
        { id: 'soc-municipal', n: 'Socialismo municipal', y: '1890–', d: 'Transformación desde el ayuntamiento: agua, transporte y vivienda públicos.', t: 'Lo local es el laboratorio de lo posible.', c: 'Competencias y presupuesto limitados.', kw: ['municipalizar', 'vivienda pública', 'remunicipalización'] },
        { id: 'soc-ecosocialismo', n: 'Ecosocialismo', y: '1970–', d: 'La crisis ecológica como consecuencia directa de la acumulación capitalista.', t: 'No hay transición ecológica sin cambio de propiedad.', c: 'Debate abierto sobre decrecimiento y bienestar.', kw: ['ecosocialismo', 'decrecimiento', 'límites del crecimiento', 'capitalismo y clima'] },
        { id: 'soc-fabiano', n: 'Socialismo fabiano', y: '1884–', d: 'Gradualismo británico: permear las instituciones hasta transformarlas.', t: 'La paciencia vence a la barricada.', c: 'Criticado por elitista y tecnocrático.', kw: ['gradualismo', 'reforma paulatina', 'fabianismo'] },
        { id: 'soc-sindical', n: 'Socialismo sindical', y: 's. XIX–', d: 'El sindicato como sujeto central de la transformación.', t: 'El poder se conquista en el centro de trabajo.', c: 'Pierde fuerza con la fragmentación del empleo.', kw: ['sindicato', 'huelga general', 'negociación colectiva'] },
        { id: 'soc-cooperativista', n: 'Cooperativismo', y: '1844–', d: 'Rochdale, Mondragón: propiedad colectiva de la empresa.', t: 'Un socio, un voto.', c: 'Dificultad para captar capital y crecer.', kw: ['cooperativa', 'un socio un voto', 'economía social'] },
        { id: 'soc-agrario', n: 'Socialismo agrario', y: 's. XIX–XX', d: 'Reparto de la tierra y protagonismo campesino.', t: 'La tierra para quien la trabaja.', c: 'Chocó con la industrialización forzada.', kw: ['reforma agraria', 'reparto de tierras', 'campesinado'] },
        { id: 'soc-humanista', n: 'Socialismo humanista', y: 's. XX', d: 'Fromm, joven Marx: superar la alienación, no solo repartir renta.', t: 'El fin es el desarrollo humano pleno.', c: 'Poco operativo como programa de gobierno.', kw: ['alienación', 'desarrollo humano', 'humanismo socialista'] },
        { id: 'soc-nacional-hist', n: 'Socialismo nacional (histórico)', y: '1900–1930', d: 'Corrientes que subordinaron la lucha de clases a la nación. Antecedente directo de derivas fascistas.', t: 'La nación como sujeto de la redención social.', c: 'Camino histórico hacia el nacionalsocialismo y el fascismo.', kw: ['socialismo nacional', 'nación por encima de clase'], risk: 2 },
        { id: 'soc-reformista', n: 'Socialismo reformista', y: '1900–', d: 'Bernstein: mejorar el capitalismo hasta transformarlo.', t: 'El movimiento lo es todo, el fin último nada.', c: 'Acusado de administrar aquello que decía superar.', kw: ['reformismo', 'socialdemocracia', 'mejorar el sistema'] },
        { id: 'soc-participativo', n: 'Socialismo participativo', y: '1990–', d: 'Parecon: planificación democrática desde consejos de consumo y producción.', t: 'Decidir juntos qué y cómo producir.', c: 'Alto coste deliberativo, nunca probado a escala.', kw: ['presupuesto participativo', 'planificación democrática', 'parecon'] }
      ]
    },
    /* ---------------------------------------------------------------- 04 */
    {
      id: 'comunismo', n: 'Comunismo y marxismo', code: 'COM',
      blurb: 'Abolición de la propiedad privada de los medios de producción y de las clases.',
      items: [
        { id: 'com-leninismo', n: 'Leninismo', y: '1902–1924', d: 'Partido de vanguardia y toma del Estado como palanca revolucionaria.', t: 'Sin dirección organizada no hay revolución.', c: 'La vanguardia sustituyó a la clase y luego a la sociedad entera.', kw: ['partido de vanguardia', 'dictadura del proletariado', 'centralismo democrático'], risk: 2 },
        { id: 'com-trotskismo', n: 'Trotskismo', y: '1920–', d: 'Revolución permanente e internacional frente al socialismo en un solo país.', t: 'O se extiende o degenera en burocracia.', c: 'Nunca gobernó; sus diagnósticos siguen siendo teóricos.', kw: ['revolución permanente', 'cuarta internacional', 'antiburocrático'], risk: 1 },
        { id: 'com-maoismo', n: 'Maoísmo', y: '1949–1976', d: 'Campesinado como sujeto revolucionario y guerra popular prolongada.', t: 'Cercar la ciudad desde el campo.', c: 'El Gran Salto Adelante provocó una hambruna de decenas de millones de muertos.', kw: ['guerra popular', 'campesinado revolucionario', 'gran salto'], risk: 2 },
        { id: 'com-estalinismo', n: 'Estalinismo', y: '1924–1953', d: 'Partido único, terror de Estado, colectivización forzosa y culto al líder.', t: 'Socialismo en un solo país impuesto por el aparato.', c: 'Gulag, Gran Purga y Holodomor: millones de muertos.', kw: ['purgas', 'gulag', 'colectivización forzosa', 'culto al líder'], risk: 3, why: 'El estalinismo convirtió un proyecto de emancipación en una máquina de exterminio administrativo: colectivización forzosa con hambrunas masivas (Holodomor, ~3,5–5 millones de muertos en Ucrania, 1932-33), el Gran Terror de 1937-38 con cientos de miles de ejecuciones sumarias, y un sistema de campos que procesó a millones de personas. La disidencia se castigaba como traición y las cifras económicas se falsificaban en cadena.' },
        { id: 'com-titoismo', n: 'Titoísmo', y: '1948–1980', d: 'Vía yugoslava: autogestión, no alineamiento y ruptura con Moscú.', t: 'Socialismo sin tutela soviética.', c: 'Partido único y represión de la disidencia pese a la apertura.', kw: ['no alineados', 'vía yugoslava', 'autogestión socialista'], risk: 2 },
        { id: 'com-luxemburgismo', n: 'Luxemburguismo', y: '1900–1919', d: 'Rosa Luxemburgo: espontaneidad de masas y crítica temprana al autoritarismo bolchevique.', t: '"Libertad es siempre la del que piensa distinto".', c: 'Sin modelo organizativo concreto que lo sostuviera.', kw: ['espontaneidad de masas', 'huelga de masas', 'libertad del disidente'] },
        { id: 'com-eurocomunismo', n: 'Eurocomunismo', y: '1970–1980', d: 'Berlinguer, Carrillo: aceptación del pluralismo y ruptura con Moscú.', t: 'Comunismo compatible con la democracia parlamentaria.', c: 'Perdió identidad frente a la socialdemocracia.', kw: ['eurocomunismo', 'vía democrática', 'ruptura con moscú'] },
        { id: 'com-consejismo', n: 'Comunismo de consejos', y: '1918–', d: 'Pannekoek, Gorter: los consejos obreros sustituyen al partido y al Estado.', t: 'La clase se emancipa por sí misma.', c: 'Casi sin implantación histórica duradera.', kw: ['consejos obreros', 'sin partido', 'autoorganización'] },
        { id: 'com-izquierda', n: 'Comunismo de izquierda', y: '1918–', d: 'Bordiga y otros: rechazo del parlamentarismo y de los frentes populares.', t: 'Ninguna concesión al reformismo.', c: 'Aislamiento político casi total.', kw: ['antiparlamentarismo', 'ultraizquierda', 'bordiguismo'] },
        { id: 'com-libertario', n: 'Comunismo libertario', y: '1876–', d: 'Kropotkin: comunismo sin Estado, a cada cual según su necesidad.', t: 'Apoyo mutuo en lugar de coerción.', c: 'Problema no resuelto de coordinación a gran escala.', kw: ['anarcocomunismo', 'apoyo mutuo', 'según necesidades'] },
        { id: 'com-primitivo', n: 'Comunismo primitivo', y: 'prehistoria', d: 'Categoría antropológica: sociedades sin clases ni propiedad privada.', t: 'La desigualdad no es un dato natural.', c: 'Los datos etnográficos son más variados que el modelo.', kw: ['sociedades sin clases', 'antropología', 'antes de la propiedad'] },
        { id: 'com-guerra', n: 'Comunismo de guerra', y: '1918–1921', d: 'Requisas forzosas y militarización de la economía en la guerra civil rusa.', t: 'Todo al frente, cueste lo que cueste.', c: 'Hambruna de 1921 y revuelta de Kronstadt.', kw: ['requisas', 'economía de guerra', 'militarización'], risk: 2 },
        { id: 'com-occidental', n: 'Marxismo occidental', y: '1920–', d: 'Gramsci, Lukács, Escuela de Frankfurt: cultura, hegemonía e ideología.', t: 'El poder también se sostiene con consenso.', c: 'Distanciado de la práctica política concreta.', kw: ['hegemonía', 'escuela de frankfurt', 'crítica cultural'] },
        { id: 'com-analitico', n: 'Marxismo analítico', y: '1980–', d: 'Cohen, Roemer: reconstruir a Marx con lógica y elección racional.', t: 'Rigor formal en lugar de dialéctica.', c: 'Pierde la dimensión histórica del original.', kw: ['marxismo analítico', 'elección racional', 'rigor formal'] },
        { id: 'com-estructuralista', n: 'Marxismo estructuralista', y: '1960–', d: 'Althusser: las estructuras determinan; el sujeto es un efecto.', t: 'Ideología como aparato material del Estado.', c: 'Determinismo que deja poco espacio a la agencia.', kw: ['althusser', 'aparatos ideológicos', 'estructura'] },
        { id: 'com-humanista', n: 'Marxismo humanista', y: '1950–', d: 'Recupera los Manuscritos de 1844 y la alienación frente al dogma.', t: 'El centro es la persona alienada, no la ley histórica.', c: 'Acusado de diluir el análisis de clase.', kw: ['manuscritos de 1844', 'alienación', 'marxismo humanista'] },
        { id: 'com-cultural', n: 'Marxismo cultural (categoría académica)', y: '1930–', d: 'Etiqueta académica para el análisis marxista de la cultura. Nota: la versión conspirativa que circula en redes es una reelaboración del bulo nazi del "bolchevismo cultural" y no describe ninguna corriente real.', t: 'La cultura reproduce relaciones de poder.', c: 'Su nombre ha sido secuestrado por la desinformación.', kw: ['marxismo cultural', 'crítica de la cultura'] },
        { id: 'com-autonomo', n: 'Autonomismo', y: '1960–', d: 'Negri, obrerismo italiano: autonomía obrera fuera de partidos y sindicatos.', t: 'La lucha precede y empuja al capital.', c: 'Sectores derivaron hacia la violencia armada en los años 70.', kw: ['autonomía obrera', 'obrerismo', 'multitud'], risk: 1 }
      ]
    },
    /* ---------------------------------------------------------------- 05 */
    {
      id: 'anarquismo', n: 'Anarquismo', code: 'ANA',
      blurb: 'Rechazo de toda autoridad no justificada: sin Estado, sin jerarquías impuestas.',
      items: [
        { id: 'ana-clasico', n: 'Anarquismo clásico', y: '1840–1936', d: 'Proudhon, Bakunin, Kropotkin: abolición del Estado y federación libre.', t: 'Ninguna autoridad sin consentimiento.', c: 'Vulnerable frente a poderes organizados y armados.', kw: ['abolir el estado', 'sin jerarquías', 'federación libre', 'anarquía'] },
        { id: 'ana-comunismo', n: 'Anarcocomunismo', y: '1876–', d: 'Propiedad común y distribución según necesidad, sin Estado.', t: 'De cada cual según capacidad, a cada cual según necesidad.', c: 'Coordinación económica sin precios ni plan.', kw: ['anarcocomunismo', 'sin dinero', 'según necesidad'] },
        { id: 'ana-sindicalismo', n: 'Anarcosindicalismo', y: '1900–', d: 'CNT, IWW: el sindicato revolucionario como germen de la nueva sociedad.', t: 'Acción directa y huelga general expropiadora.', c: 'Depende de un tejido industrial que ya casi no existe.', kw: ['cnt', 'acción directa', 'huelga general', 'sindicalismo revolucionario'] },
        { id: 'ana-mutualismo', n: 'Mutualismo', y: '1840–', d: 'Proudhon: crédito mutuo, posesión en uso y contratos libres.', t: 'Propiedad como uso, no como renta.', c: 'Difícil de sostener frente al capital concentrado.', kw: ['crédito mutuo', 'banca popular', 'posesión'] },
        { id: 'ana-individualista', n: 'Anarquismo individualista', y: '1844–', d: 'Stirner, Tucker: soberanía del individuo frente a toda abstracción.', t: 'Ni Estado, ni Dios, ni sociedad por encima del yo.', c: 'Escaso proyecto colectivo.', kw: ['soberanía individual', 'stirner', 'egoísmo'] },
        { id: 'ana-social', n: 'Anarquismo social', y: 's. XIX–', d: 'Rama colectivista frente a la individualista: libertad en comunidad.', t: 'La libertad se construye con otros.', c: 'Tensión permanente con el ala individualista.', kw: ['anarquismo social', 'comunidad libertaria'] },
        { id: 'ana-colectivista', n: 'Anarcocolectivismo', y: '1868–', d: 'Bakunin: medios colectivos, retribución según trabajo aportado.', t: 'Colectivizar sin abolir la remuneración.', c: 'Puesto en cuestión por el anarcocomunismo.', kw: ['colectivizar', 'según trabajo', 'bakunin'] },
        { id: 'ana-verde', n: 'Anarquismo verde', y: '1970–', d: 'Antiautoritarismo y ecología: descentralizar y reducir escala.', t: 'La dominación de la naturaleza replica la dominación social.', c: 'Poca respuesta a problemas de escala global.', kw: ['ecología libertaria', 'descentralización', 'antiindustrial'] },
        { id: 'ana-ecoanarquismo', n: 'Ecoanarquismo', y: '1980–', d: 'Acción directa ecologista sin mediación institucional.', t: 'Defender el territorio aquí y ahora.', c: 'Sectores minoritarios han recurrido al sabotaje violento.', kw: ['acción directa ecologista', 'defensa del territorio'], risk: 1 },
        { id: 'ana-primitivismo', n: 'Anarcoprimitivismo', y: '1980–', d: 'Zerzan: la civilización industrial es la fuente del problema.', t: 'Volver a formas de vida preindustriales.', c: 'La desindustrialización rápida implicaría una mortalidad masiva.', kw: ['antitecnología', 'volver a la naturaleza', 'contra la civilización'], risk: 1 },
        { id: 'ana-feminismo', n: 'Anarcofeminismo', y: '1900–', d: 'Goldman, Mujeres Libres: patriarcado y Estado como jerarquías gemelas.', t: 'No hay libertad sin abolir la dominación de género.', c: 'Fricciones con feminismos institucionales.', kw: ['mujeres libres', 'patriarcado y estado', 'anarcofeminismo'] },
        { id: 'ana-insurreccional', n: 'Anarquismo insurreccional', y: '1880–', d: 'Acción directa inmediata y células informales; incluye la tradición de "propaganda por el hecho".', t: 'No esperar a las condiciones: crearlas.', c: 'Su ala violenta cometió atentados con víctimas civiles.', kw: ['propaganda por el hecho', 'insurrección', 'célula informal'], risk: 2 },
        { id: 'ana-pacifista', n: 'Anarquismo pacifista', y: '1900–', d: 'Tolstói: rechazo simultáneo del Estado y de la violencia.', t: 'Los medios prefiguran los fines.', c: 'Cuestionado ante regímenes que sí usan la fuerza.', kw: ['no violencia', 'objeción de conciencia', 'tolstói'] },
        { id: 'ana-cristiano', n: 'Anarquismo cristiano', y: '1880–', d: 'El Sermón de la Montaña sin jerarquía eclesiástica ni Estado.', t: 'Ningún señor sobre la tierra.', c: 'Marginal en ambas tradiciones.', kw: ['sermón de la montaña', 'sin jerarquía eclesial'] },
        { id: 'ana-queer', n: 'Anarquismo queer', y: '1990–', d: 'Contra la normatividad de género y sexual como estructura de poder.', t: 'Liberar el deseo es también política.', c: 'Acusado de fragmentar el sujeto de la lucha.', kw: ['queer', 'antinormativo', 'liberación sexual'] },
        { id: 'ana-plataformismo', n: 'Plataformismo', y: '1926–', d: 'Makhno, Arshinov: organización anarquista con unidad táctica y responsabilidad colectiva.', t: 'La eficacia requiere estructura.', c: 'Acusado de reintroducir centralismo.', kw: ['plataforma', 'unidad táctica', 'organización específica'] },
        { id: 'ana-especifismo', n: 'Especifismo', y: '1950–', d: 'Vertiente sudamericana: organización específica inserta en movimientos sociales.', t: 'Trabajo de base antes que vanguardia.', c: 'Implantación limitada fuera del Cono Sur.', kw: ['especifismo', 'inserción social', 'trabajo de base'] },
        { id: 'ana-postizquierda', n: 'Anarquismo postizquierdista', y: '1990–', d: 'Ruptura con la izquierda organizada, la ideología y la militancia formal.', t: 'Ni programa, ni organización, ni deber militante.', c: 'Nihilismo político sin propuesta constructiva.', kw: ['postizquierda', 'antimilitancia', 'nihilismo'] },
        { id: 'ana-posmoderno', n: 'Postanarquismo', y: '1990–', d: 'Cruce con Foucault y Deleuze: el poder es difuso, no un centro a tomar.', t: 'No hay un palacio de invierno que asaltar.', c: 'Muy abstracto para la práctica política.', kw: ['postanarquismo', 'poder difuso', 'microfísica'] },
        { id: 'ana-municipalismo', n: 'Municipalismo libertario', y: '1980–', d: 'Bookchin: asambleas municipales confederadas sustituyen al Estado.', t: 'Democracia directa a escala de ciudad.', c: 'Cuestión abierta: cómo gestionar lo transnacional.', kw: ['bookchin', 'asamblea municipal', 'confederalismo democrático'] }
      ]
    },
    /* ---------------------------------------------------------------- 06 */
    {
      id: 'libertarismo', n: 'Libertarismo', code: 'LBT',
      blurb: 'Principio de no agresión y reducción radical del poder estatal.',
      items: [
        { id: 'lbt-derecha', n: 'Libertarismo de derecha', y: '1960–', d: 'Nozick, Rothbard: propiedad privada absoluta y Estado casi inexistente.', t: 'Impuesto = coerción sobre el fruto del trabajo.', c: 'No explica quién financia bienes públicos y externalidades.', kw: ['no agresión', 'impuestos son robo', 'propiedad absoluta'] },
        { id: 'lbt-izquierda', n: 'Libertarismo de izquierda', y: '1970–', d: 'Libertad individual máxima con recursos naturales de titularidad común.', t: 'Tu cuerpo es tuyo; la tierra es de todos.', c: 'Difícil traducción institucional.', kw: ['libertarismo de izquierda', 'recursos comunes', 'renta de la tierra'] },
        { id: 'lbt-minarquismo', n: 'Minarquismo', y: '1970–', d: 'Estado reducido a justicia, policía y defensa.', t: 'Solo hace falta el "Estado vigilante nocturno".', c: 'Ese mínimo tiende a crecer o a colapsar.', kw: ['estado mínimo', 'solo justicia y defensa', 'guardián nocturno'] },
        { id: 'lbt-anarcocapitalismo', n: 'Anarcocapitalismo', y: '1970–', d: 'Rothbard: justicia, seguridad y moneda provistas por el mercado.', t: 'Todo servicio estatal puede privatizarse.', c: 'Agencias de seguridad privadas competidoras derivan en poder armado privado.', kw: ['anarcocapitalismo', 'privatizar la justicia', 'seguridad privada'], risk: 1 },
        { id: 'lbt-voluntarismo', n: 'Voluntarismo', y: '1990–', d: 'Toda relación humana debe ser voluntaria y revocable.', t: 'Consentimiento como única fuente de legitimidad.', c: 'Ignora asimetrías de poder que vician el consentimiento.', kw: ['voluntario', 'consentimiento', 'asociación libre'] },
        { id: 'lbt-agorismo', n: 'Agorismo', y: '1975–', d: 'Konkin: mercados grises y negros como estrategia de erosión del Estado.', t: 'Contraeconomía en lugar de elecciones.', c: 'Estrategia inviable a escala.', kw: ['contraeconomía', 'mercado negro', 'agorismo'] },
        { id: 'lbt-geolibertarismo', n: 'Geolibertarismo', y: '1879–', d: 'Henry George: libertad plena salvo un impuesto único sobre el valor del suelo.', t: 'La tierra no la creó nadie; su renta es común.', c: 'Base fiscal insuficiente para un Estado moderno.', kw: ['impuesto único', 'valor del suelo', 'georgismo'] },
        { id: 'lbt-paleolibertarismo', n: 'Paleolibertarismo', y: '1990–', d: 'Alianza entre libertarismo económico y conservadurismo cultural duro.', t: 'Libertad de mercado con orden social tradicional.', c: 'Ha servido de puerta de entrada a la derecha identitaria.', kw: ['paleolibertario', 'mercado y tradición'], risk: 1 },
        { id: 'lbt-civil', n: 'Libertarismo civil', y: 's. XX–', d: 'Foco en libertades civiles: privacidad, expresión, drogas, vigilancia.', t: 'El Estado no vigila ni tutela al adulto.', c: 'Poca atención al poder corporativo sobre los datos.', kw: ['privacidad', 'legalización', 'contra la vigilancia', 'libertades civiles'] },
        { id: 'lbt-economico', n: 'Libertarismo económico', y: 's. XX–', d: 'Desregulación total, moneda competitiva, comercio sin trabas.', t: 'El mercado se autorregula mejor que el legislador.', c: 'Las crisis financieras desmienten la autorregulación completa.', kw: ['desregulación total', 'banca libre', 'moneda competitiva'] },
        { id: 'lbt-tecnologico', n: 'Tecnolibertarismo', y: '1990–', d: 'Criptografía, redes y cripto como salida técnica del control estatal.', t: 'El código es más eficaz que la ley.', c: 'Sustituye poder estatal por poder de plataformas y protocolos.', kw: ['cripto', 'cifrado', 'descentralización tecnológica', 'blockchain'] }
      ]
    },
    /* ---------------------------------------------------------------- 07 */
    {
      id: 'democracia', n: 'Democracia (modelos)', code: 'DEM',
      blurb: 'Formas de organizar el autogobierno colectivo.',
      items: [
        { id: 'dem-liberal', n: 'Democracia liberal', y: 's. XIX–', d: 'Elecciones libres, derechos garantizados, contrapesos y prensa libre.', t: 'La mayoría manda, pero no todo.', c: 'Fatiga institucional y captura por intereses económicos.', kw: ['elecciones libres', 'contrapesos', 'estado de derecho'] },
        { id: 'dem-representativa', n: 'Democracia representativa', y: 's. XVIII–', d: 'El pueblo delega en representantes electos y revocables por urna.', t: 'Gobernar a escala exige delegación.', c: 'Distancia creciente entre representantes y representados.', kw: ['representantes', 'parlamento', 'delegación'] },
        { id: 'dem-directa', n: 'Democracia directa', y: 'Atenas; Suiza', d: 'Los ciudadanos deciden sin intermediarios.', t: 'Nadie decide por ti lo que puedes decidir tú.', c: 'Riesgo de decisiones mayoritarias contra minorías.', kw: ['referéndum', 'asamblea', 'que decida el pueblo', 'votar todo'] },
        { id: 'dem-participativa', n: 'Democracia participativa', y: '1980–', d: 'Presupuestos participativos y codecisión continua.', t: 'Participar no es solo votar cada cuatro años.', c: 'Participa siempre la misma minoría activa.', kw: ['presupuesto participativo', 'participación ciudadana'] },
        { id: 'dem-deliberativa', n: 'Democracia deliberativa', y: '1990–', d: 'Habermas; asambleas ciudadanas por sorteo con expertos.', t: 'La legitimidad nace de la deliberación informada.', c: 'Lenta y difícil de escalar.', kw: ['asamblea ciudadana', 'sorteo cívico', 'deliberación'] },
        { id: 'dem-plebiscitaria', n: 'Democracia plebiscitaria', y: 's. XIX–', d: 'Consultas convocadas por el líder para validar su poder.', t: 'Apelación directa al pueblo por encima de las instituciones.', c: 'Herramienta clásica de legitimación autoritaria.', kw: ['plebiscito', 'consulta del líder', 'apelar al pueblo'], risk: 1 },
        { id: 'dem-parlamentaria', n: 'Democracia parlamentaria', y: 's. XVIII–', d: 'El ejecutivo emana del parlamento y responde ante él.', t: 'Gobierno con confianza de la cámara.', c: 'Inestabilidad con parlamentos fragmentados.', kw: ['parlamentarismo', 'moción de censura', 'investidura'] },
        { id: 'dem-presidencial', n: 'Democracia presidencial', y: '1787–', d: 'Presidente electo con legitimidad propia y separado del legislativo.', t: 'Doble legitimidad, poderes separados.', c: 'Bloqueos institucionales sin salida ordenada.', kw: ['presidencialismo', 'presidente electo'] },
        { id: 'dem-semipresidencial', n: 'Democracia semipresidencial', y: '1958–', d: 'Presidente y primer ministro comparten el ejecutivo.', t: 'Combina estabilidad y responsabilidad parlamentaria.', c: 'Cohabitaciones paralizantes.', kw: ['semipresidencial', 'cohabitación'] },
        { id: 'dem-cristiana', n: 'Democracia cristiana', y: '1945–', d: 'Doctrina social cristiana con economía social de mercado.', t: 'Bien común, subsidiariedad y solidaridad.', c: 'Difuminada en el centroderecha genérico.', kw: ['democracia cristiana', 'bien común', 'subsidiariedad'] },
        { id: 'dem-social', n: 'Socialdemocracia', y: '1900–', d: 'Capitalismo regulado, Estado del bienestar fuerte y negociación colectiva.', t: 'Mercado domesticado por la política democrática.', c: 'Erosionada por la globalización financiera.', kw: ['socialdemocracia', 'estado del bienestar', 'impuestos progresivos', 'pacto social'] },
        { id: 'dem-popular', n: '"Democracia popular"', y: '1945–1989', d: 'Denominación de los regímenes de partido único del bloque soviético.', t: 'Se presentaba como democracia superior sin pluralismo.', c: 'Sin elecciones competitivas: democracia solo de nombre.', kw: ['democracia popular', 'partido único', 'bloque del este'], risk: 2 },
        { id: 'dem-digital', n: 'Democracia digital', y: '2000–', d: 'Plataformas de participación, voto y consulta en línea.', t: 'La tecnología abarata la participación.', c: 'Brecha digital, seguridad del voto y manipulación algorítmica.', kw: ['voto electrónico', 'participación online', 'gobierno abierto'] },
        { id: 'dem-liquida', n: 'Democracia líquida', y: '2000–', d: 'Voto delegable y revocable en cualquier momento y por materia.', t: 'Delegas en quien sabe, cuando quieres.', c: 'Concentración de delegaciones en pocos nodos.', kw: ['voto delegado', 'democracia líquida'] },
        { id: 'dem-consensual', n: 'Democracia consensual', y: '1968–', d: 'Lijphart: reparto de poder entre comunidades, vetos mutuos.', t: 'En sociedades divididas, ganar el 51 % no basta.', c: 'Puede cristalizar la división que pretende gestionar.', kw: ['consociativa', 'reparto de poder', 'veto mutuo'] },
        { id: 'dem-radical', n: 'Democracia radical', y: '1985–', d: 'Laclau y Mouffe: el conflicto es constitutivo, no un fallo del sistema.', t: 'Agonismo en lugar de consenso forzado.', c: 'Riesgo de polarización permanente.', kw: ['agonismo', 'conflicto político', 'democracia radical'] }
      ]
    },
    /* ---------------------------------------------------------------- 08 */
    {
      id: 'nacionalismo', n: 'Nacionalismo', code: 'NAC',
      blurb: 'La nación como sujeto político central. Va de lo cívico e inclusivo a lo étnico y excluyente.',
      items: [
        { id: 'nac-civico', n: 'Nacionalismo cívico', y: 's. XVIII–', d: 'Pertenencia por adhesión a instituciones y leyes compartidas, no por origen.', t: 'Es de aquí quien participa del pacto cívico.', c: 'Puede exigir asimilación cultural implícita.', kw: ['nacionalismo cívico', 'ciudadanía compartida', 'pacto constitucional'] },
        { id: 'nac-etnico', n: 'Nacionalismo étnico', y: 's. XIX–', d: 'La nación se define por ascendencia y sangre.', t: 'La pertenencia se hereda, no se adquiere.', c: 'Excluye estructuralmente y ha alimentado limpiezas étnicas.', kw: ['sangre y suelo', 'ascendencia', 'nación étnica', 'pureza del pueblo'], risk: 2 },
        { id: 'nac-cultural', n: 'Nacionalismo cultural', y: 's. XIX–', d: 'Lengua, costumbres y memoria como núcleo de la nación.', t: 'La cultura común crea comunidad política.', c: 'Presión sobre las minorías internas.', kw: ['identidad cultural', 'tradiciones nacionales'] },
        { id: 'nac-linguistico', n: 'Nacionalismo lingüístico', y: 's. XIX–', d: 'La lengua propia como frontera y motor de la nación.', t: 'Sin lengua no hay pueblo.', c: 'Conflictos de derechos lingüísticos.', kw: ['lengua propia', 'normalización lingüística'] },
        { id: 'nac-religioso', n: 'Nacionalismo religioso', y: 's. XX–', d: 'Fusión de identidad nacional y confesión religiosa.', t: 'La nación tiene una religión verdadera.', c: 'Discrimina a minorías religiosas y ateos.', kw: ['nación católica', 'nación religiosa', 'identidad confesional'], risk: 1 },
        { id: 'nac-economico', n: 'Nacionalismo económico', y: 's. XVII–', d: 'Aranceles, industria nacional y sustitución de importaciones.', t: 'Producir en casa da soberanía.', c: 'Precios más altos y represalias comerciales.', kw: ['aranceles', 'proteccionismo', 'industria nacional', 'comprar nacional'] },
        { id: 'nac-integral', n: 'Nacionalismo integral', y: '1900–1945', d: 'Maurras: nación total, antiliberal y jerárquica.', t: 'La nación por encima de la persona y de la ley.', c: 'Base doctrinal de regímenes autoritarios europeos.', kw: ['nación total', 'maurras', 'antiliberal'], risk: 2 },
        { id: 'nac-romantico', n: 'Nacionalismo romántico', y: '1800–1850', d: 'Herder: el "espíritu del pueblo" expresado en folclore y lengua.', t: 'Cada pueblo tiene un genio propio.', c: 'Mitificó pasados inventados.', kw: ['espíritu del pueblo', 'folclore', 'romanticismo nacional'] },
        { id: 'nac-revolucionario', n: 'Nacionalismo revolucionario', y: 's. XX', d: 'Liberación nacional por vía armada frente a potencias extranjeras.', t: 'Independencia por cualquier medio.', c: 'Muchos movimientos derivaron en regímenes de partido único.', kw: ['liberación nacional', 'lucha armada'], risk: 1 },
        { id: 'nac-liberal', n: 'Nacionalismo liberal', y: 's. XIX–', d: 'Autodeterminación compatible con derechos individuales.', t: 'Naciones libres de ciudadanos libres.', c: 'Ambiguo sobre quién forma el demos.', kw: ['autodeterminación', 'nación liberal'] },
        { id: 'nac-conservador', n: 'Nacionalismo conservador', y: 's. XX–', d: 'Defensa de la nación como comunidad moral heredada.', t: 'Preservar lo que somos.', c: 'Idealiza una homogeneidad que nunca existió.', kw: ['preservar la nación', 'raíces', 'lo nuestro'], risk: 1 },
        { id: 'nac-expansionista', n: 'Nacionalismo expansionista', y: 's. XIX–XX', d: 'Reclamación de territorio ajeno como derecho nacional.', t: 'La nación necesita más espacio.', c: 'Doctrina motor de guerras de agresión.', kw: ['espacio vital', 'conquistar territorio', 'anexión'], risk: 3, why: 'La idea de que una nación tiene derecho a tomar territorio ajeno por su vitalidad, su historia o su raza es la premisa que produjo la Segunda Guerra Mundial (Lebensraum), la invasión de Manchuria y las guerras yugoslavas. En todos los casos el argumento fue el mismo y el resultado también: deportación, ocupación y limpieza étnica sobre la población que ya vivía allí.' },
        { id: 'nac-irredentista', n: 'Irredentismo', y: 's. XIX–', d: 'Reclamar territorios habitados por connacionales bajo otra soberanía.', t: 'Hay hermanos al otro lado de la frontera.', c: 'Justificación recurrente de anexiones.', kw: ['irredentismo', 'territorios perdidos', 'reunificar'], risk: 2 },
        { id: 'nac-regional', n: 'Regionalismo', y: 's. XIX–', d: 'Mayor autogobierno sin plantear la independencia.', t: 'Descentralizar sin romper.', c: 'Conflictos permanentes de competencias.', kw: ['autonomía', 'descentralización', 'autogobierno regional'] },
        { id: 'nac-separatista', n: 'Independentismo', y: 's. XIX–', d: 'Constitución de un Estado propio para una comunidad nacional.', t: 'Derecho a decidir el propio marco político.', c: 'Frecuente fractura interna de la sociedad afectada.', kw: ['independencia', 'secesión', 'estado propio'] },
        { id: 'nac-panetnico', n: 'Panetnicismo', y: 's. XIX–', d: 'Unir en una entidad a pueblos con parentesco cultural (paneslavismo, panarabismo).', t: 'Los afines deben unirse.', c: 'Usado como coartada por potencias regionales.', kw: ['paneslavismo', 'panarabismo', 'unión de pueblos hermanos'], risk: 1 },
        { id: 'nac-anticolonial', n: 'Nacionalismo anticolonial', y: '1945–1975', d: 'Independencia frente a las metrópolis coloniales.', t: 'Soberanía como reparación histórica.', c: 'Élites nacionales que replicaron la extracción colonial.', kw: ['descolonización', 'independencia colonial', 'antiimperialismo'] },
        { id: 'nac-poscolonial', n: 'Nacionalismo poscolonial', y: '1960–', d: 'Reconstrucción identitaria tras la independencia formal.', t: 'Descolonizar también la cultura y la economía.', c: 'A veces usado para blindar gobiernos autoritarios.', kw: ['poscolonial', 'neocolonialismo', 'soberanía económica'] },
        { id: 'nac-ultra', n: 'Ultranacionalismo', y: 's. XX–', d: 'Culto a la nación con desprecio y deshumanización del extranjero.', t: 'La nación por encima de todo y de todos.', c: 'Precursor directo del fascismo y de la violencia de masas.', kw: ['la nación por encima de todo', 'odio al extranjero', 'nación superior', 'expulsar extranjeros'], risk: 3, why: 'El ultranacionalismo funciona deshumanizando a quien queda fuera de la nación imaginada. Ese paso —de "no son de los nuestros" a "sobran"— precede a todas las grandes matanzas del siglo XX: Armenia 1915, Alemania 1933-45, Ruanda 1994, Bosnia 1992-95. La escalada es documentada y siempre empieza en el lenguaje, no en las armas.' }
      ]
    },
    /* ---------------------------------------------------------------- 09 */
    {
      id: 'fascismo', n: 'Fascismo y afines', code: 'FAS',
      blurb: 'Ultranacionalismo palingenésico: renacimiento nacional por la fuerza, culto al líder y liquidación del pluralismo.',
      items: [
        { id: 'fas-italiano', n: 'Fascismo italiano', y: '1922–1945', d: 'Mussolini: Estado totalitario, partido único, corporativismo y guerra como higiene.', t: '"Todo en el Estado, nada fuera del Estado".', c: 'Leyes raciales de 1938, guerra colonial con gas en Etiopía, 25 años de dictadura.', kw: ['mussolini', 'todo en el estado', 'partido único', 'estado totalitario'], risk: 3, why: 'El fascismo italiano abolió sindicatos, prensa libre y partidos en tres años; asesinó a la oposición (Matteotti, 1924); usó gas mostaza contra población civil en Etiopía; y aprobó en 1938 leyes raciales que despojaron a los judíos italianos de trabajo, escuela y ciudadanía, preparando su deportación posterior. Prometió orden y entregó guerra, ruina y ocupación extranjera.' },
        { id: 'fas-nazismo', n: 'Nacionalsocialismo', y: '1933–1945', d: 'Hitler: racismo biológico de Estado, Führerprinzip, guerra de conquista y exterminio industrial.', t: 'Raza, espacio vital y liderazgo absoluto.', c: 'Shoah: seis millones de judíos asesinados; ~5 millones más de víctimas del sistema; 50-60 millones de muertos en la guerra.', kw: ['hitler', 'raza aria', 'nacionalsocialismo', 'espacio vital', 'führer', 'tercer reich', 'supremacía racial'], risk: 3, why: 'El nazismo llevó al Estado a organizar el asesinato industrial de seis millones de judíos, más el exterminio de gitanos, personas con discapacidad (Aktion T4), homosexuales, prisioneros soviéticos y opositores políticos. Desencadenó la guerra más letal de la historia. No fracasó por "aplicarse mal": el genocidio era el programa, escrito y planificado desde el inicio. La evidencia —documentos, contabilidad de los campos, testimonios, los propios juicios de Núremberg— es la más extensa de cualquier crimen del siglo XX.' },
        { id: 'fas-falangismo', n: 'Falangismo', y: '1933–1975', d: 'España: nacionalsindicalismo, unidad de destino, sindicato vertical.', t: 'Nación imperial y católica sin lucha de clases.', c: 'Sostuvo cuatro décadas de dictadura, represión y campos de trabajo.', kw: ['falange', 'nacionalsindicalismo', 'unidad de destino'], risk: 3, why: 'El falangismo aportó la armazón ideológica del régimen franquista: partido único, sindicato vertical obligatorio, censura previa y tribunales militares para delitos políticos. La represión de posguerra ejecutó a decenas de miles de personas y llenó cárceles y batallones de trabajos forzados. Su "unidad" consistía en eliminar físicamente a quien discrepara.' },
        { id: 'fas-rexismo', n: 'Rexismo', y: '1935–1945', d: 'Bélgica, Degrelle: fascismo católico que acabó colaborando con la ocupación nazi.', t: 'Regeneración nacional y católica.', c: 'Colaboracionismo y reclutamiento para las Waffen-SS.', kw: ['rexismo', 'degrelle'], risk: 3, why: 'El rexismo pasó del catolicismo regeneracionista al colaboracionismo directo: reclutó belgas para las Waffen-SS y participó en la represión de la resistencia y en la entrega de judíos. Muestra la trayectoria típica de estos movimientos: empiezan pidiendo limpieza moral y terminan en la ocupación extranjera.' },
        { id: 'fas-austrofascismo', n: 'Austrofascismo', y: '1934–1938', d: 'Dollfuss: Estado corporativo católico, disolución del parlamento.', t: 'Orden cristiano autoritario contra marxismo y nazismo.', c: 'Guerra civil de febrero de 1934 y campos de internamiento.', kw: ['austrofascismo', 'dollfuss', 'estado corporativo'], risk: 3, why: 'El austrofascismo suspendió el parlamento, bombardeó con artillería viviendas obreras en Viena en 1934, ilegalizó partidos y creó campos de internamiento para opositores. Su autoritarismo dejó al país sin defensas democráticas y facilitó la anexión nazi cuatro años después.' },
        { id: 'fas-integralismo', n: 'Integralismo brasileño', y: '1932–1937', d: 'Plínio Salgado: milicia de camisas verdes, lema "Dios, Patria y Familia".', t: 'Nación integral bajo autoridad espiritual.', c: 'Violencia paramilitar e intento de golpe en 1938.', kw: ['integralismo', 'camisas verdes', 'plinio salgado'], risk: 3, why: 'El integralismo organizó milicias uniformadas que asaltaron sedes sindicales y de izquierda, e intentó un golpe armado contra el propio gobierno de Vargas en 1938. Su modelo de "armonía nacional" pasaba por eliminar por la fuerza a quien no encajara en él.' },
        { id: 'fas-guardia-hierro', n: 'Guardia de Hierro', y: '1927–1941', d: 'Rumanía, Codreanu: fascismo místico-ortodoxo con culto a la muerte.', t: 'Redención nacional por sacrificio y violencia.', c: 'Asesinatos políticos y pogromo de Bucarest (1941).', kw: ['guardia de hierro', 'codreanu', 'legionarios'], risk: 3, why: 'La Guardia de Hierro asesinó a dos primeros ministros y organizó en enero de 1941 el pogromo de Bucarest, donde más de un centenar de judíos fueron torturados y asesinados, algunos en un matadero municipal. Su misticismo del sacrificio era, en la práctica, licencia para matar.' },
        { id: 'fas-clerical', n: 'Fascismo clerical', y: '1930–1945', d: 'Fusión de autoridad religiosa y Estado fascista (Eslovaquia de Tiso, Croacia ustacha).', t: 'La nación como misión sagrada.', c: 'El Estado ustacha ejecutó genocidio en Jasenovac.', kw: ['fascismo clerical', 'ustacha', 'tiso', 'estado sagrado'], risk: 3, why: 'El fascismo clerical dio cobertura sagrada al exterminio: la Eslovaquia de Tiso deportó a unos 58.000 judíos a campos de la muerte, y el Estado ustacha croata asesinó en Jasenovac a decenas de miles de serbios, judíos y gitanos, con conversiones forzadas incluidas. Invocar a Dios no atenuó el crimen: lo justificó.' },
        { id: 'fas-revolucionario', n: 'Fascismo revolucionario', y: '1919–1945', d: 'Ala "izquierda" del fascismo: anticapitalista en el discurso, totalitaria en la práctica.', t: 'Revolución nacional contra burguesía y marxismo.', c: 'Su anticapitalismo se abandonó al llegar al poder.', kw: ['fascismo de izquierda', 'revolución nacional'], risk: 3, why: 'La retórica anticapitalista del fascismo revolucionario se evaporó en cuanto hubo poder: en Italia y Alemania los grandes grupos industriales conservaron sus beneficios mientras los sindicatos eran disueltos y sus dirigentes encarcelados. La "revolución" consistió en suprimir a la izquierda, no al capital.' },
        { id: 'fas-corporativista', n: 'Corporativismo fascista', y: '1926–1945', d: 'Sindicatos y patronal fundidos en corporaciones estatales; huelga prohibida.', t: 'Armonía de clases dirigida por el Estado.', c: 'En la práctica: salarios a la baja y trabajadores sin defensa.', kw: ['corporativismo', 'sindicato vertical', 'prohibir la huelga'], risk: 3, why: 'El corporativismo fascista eliminó la huelga y la negociación libre; con los trabajadores sin herramientas de presión, los salarios reales italianos cayeron durante los años treinta. La "armonía de clases" fue en la práctica el desarme legal de una de las partes.' },
        { id: 'fas-neofascismo', n: 'Neofascismo', y: '1945–', d: 'Reelaboración de posguerra: menos uniformes, misma matriz identitaria y antiliberal.', t: 'Recuperar el "orden natural" perdido.', c: 'Atentados de la estrategia de la tensión, terrorismo de extrema derecha actual.', kw: ['neofascismo', 'nostalgia del régimen', 'orden natural'], risk: 3, why: 'El neofascismo no es folclore histórico: la estrategia de la tensión en Italia dejó decenas de muertos (Piazza Fontana 1969, Bolonia 1980, 85 muertos), y la violencia de extrema derecha contemporánea —Utøya 2011, Christchurch 2019, El Paso 2019— comparte marco doctrinal y se documenta hoy como una de las principales amenazas terroristas en Europa y Norteamérica.' },
        { id: 'fas-posfascismo', n: 'Posfascismo', y: '1990–', d: 'Formaciones de origen fascista que aceptan las urnas sin romper con su matriz.', t: 'Aceptación táctica de la democracia electoral.', c: 'Debate abierto sobre la sinceridad de esa conversión.', kw: ['posfascismo', 'derecha radical institucional'], risk: 2 },
        { id: 'fas-tercera-posicion', n: 'Tercera Posición', y: '1970–', d: '"Ni capitalismo ni comunismo": síntesis identitaria y antisistema.', t: 'Una tercera vía nacional y revolucionaria.', c: 'Vehículo de reciclaje del neofascismo hacia nuevos públicos.', kw: ['tercera posición', 'ni capitalismo ni comunismo', 'nacionalrevolucionario'], risk: 3, why: 'La Tercera Posición existe como envoltorio: su función histórica ha sido reciclar cuadros neofascistas presentándolos como alternativa antisistema. Los grupos que la adoptaron (Terza Posizione, Ordine Nuovo y sucesores) participaron en atentados y en redes de terrorismo negro, no en ninguna vía nueva.' },
        { id: 'fas-nacionalbolchevismo', n: 'Nacionalbolchevismo', y: '1920–', d: 'Cruce entre estética totalitaria de izquierda y ultranacionalismo.', t: 'Imperio y colectivismo contra Occidente liberal.', c: 'Reivindica simultáneamente dos totalitarismos.', kw: ['nacionalbolchevismo', 'duguin', 'eurasianismo'], risk: 3, why: 'El nacionalbolchevismo reivindica a la vez lo peor del estalinismo y lo peor del fascismo: imperio, partido único y liquidación del individuo. En su versión eurasianista contemporánea ha servido de arsenal doctrinal para justificar guerras de agresión y anexiones territoriales.' },
        { id: 'fas-nacionalrevolucionarismo', n: 'Nacionalrevolucionarismo', y: '1920–', d: 'Revolución conservadora alemana: antiliberal, antidemocrática, antiburguesa.', t: 'Destruir la modernidad liberal desde dentro.', c: 'Preparó intelectualmente el terreno al nazismo.', kw: ['revolución conservadora', 'antiliberal radical'], risk: 3, why: 'La "revolución conservadora" no cometió los crímenes directamente: los hizo pensables. Sus autores normalizaron el desprecio a la república, al parlamento y al individuo durante los años de Weimar, y ese trabajo previo fue lo que permitió que en 1933 la democracia alemana se rindiera casi sin resistencia intelectual.' }
      ]
    },
    /* ---------------------------------------------------------------- 10 */
    {
      id: 'autoritarismo', n: 'Autoritarismo y totalitarismo', code: 'AUT',
      blurb: 'Concentración del poder y supresión del control ciudadano, con o sin ideología total.',
      items: [
        { id: 'aut-militar', n: 'Dictadura militar', y: 's. XIX–', d: 'Las fuerzas armadas asumen el gobierno tras un golpe.', t: 'El ejército como "reserva moral" de la nación.', c: 'Cono Sur: desapariciones forzadas, tortura sistemática, robo de bebés.', kw: ['golpe de estado', 'junta militar', 'que gobiernen los militares'], risk: 3, why: 'Las dictaduras militares del Cono Sur dejaron ~30.000 desaparecidos en Argentina, más de 3.000 asesinados y 38.000 torturados documentados en Chile, y el robo sistemático de bebés a detenidas. En todos los casos el argumento fue "restaurar el orden temporalmente"; el resultado fue tortura institucionalizada y décadas de impunidad.' },
        { id: 'aut-civil', n: 'Autoritarismo civil', y: 's. XX–', d: 'Gobiernos electos que vacían tribunales, prensa y oposición desde dentro.', t: 'Mayoría electoral usada para desmontar contrapesos.', c: 'Es el modo dominante de retroceso democrático actual.', kw: ['controlar los jueces', 'someter la prensa', 'reformar el tribunal', 'mayoría sin límites'], risk: 2 },
        { id: 'aut-cesarismo', n: 'Cesarismo', y: 'Roma; s. XIX–', d: 'Líder providencial que concentra poderes en nombre del pueblo.', t: 'Un hombre encarna la voluntad nacional.', c: 'Elimina la alternancia por definición.', kw: ['líder providencial', 'hombre fuerte', 'plenos poderes'], risk: 2 },
        { id: 'aut-bonapartismo', n: 'Bonapartismo', y: '1799–', d: 'Poder personal legitimado por plebiscitos y por el ejército.', t: 'Autoridad plebiscitaria por encima de los partidos.', c: 'Democracia aparente sin control real.', kw: ['bonapartismo', 'plebiscito y ejército'], risk: 2 },
        { id: 'aut-personalismo', n: 'Personalismo político', y: 's. XX–', d: 'El régimen depende de una persona, no de instituciones.', t: 'La lealtad al líder sustituye a la ley.', c: 'Crisis sucesoria garantizada.', kw: ['culto a la personalidad', 'lealtad al líder'], risk: 2 },
        { id: 'aut-caudillismo', n: 'Caudillismo', y: 's. XIX–', d: 'Liderazgo carismático personal con clientelas armadas, típico de Latinoamérica.', t: 'El caudillo protege a los suyos.', c: 'Inestabilidad crónica y violencia faccional.', kw: ['caudillo', 'clientelismo armado'], risk: 2 },
        { id: 'aut-despotismo', n: 'Despotismo', y: 'antiguo–', d: 'Poder arbitrario sin límite legal ni rendición de cuentas.', t: 'La voluntad del gobernante es la ley.', c: 'Definición misma de la arbitrariedad.', kw: ['poder absoluto', 'sin límites', 'la ley soy yo'], risk: 3, why: 'El despotismo elimina la única protección real que tiene una persona frente al poder: la posibilidad de invocar una regla que también obligue a quien manda. Sin límite legal ni rendición de cuentas, la seguridad de cualquiera depende del humor del gobernante. No hay ningún caso histórico de despotismo benévolo estable: el poder arbitrario acaba usándose arbitrariamente.' },
        { id: 'aut-absolutismo', n: 'Absolutismo', y: 's. XVI–XVIII', d: 'Monarquía sin límites institucionales, legitimada por derecho divino.', t: 'El rey no responde ante nadie salvo Dios.', c: 'Superado por las revoluciones liberales.', kw: ['derecho divino', 'monarquía absoluta'], risk: 2 },
        { id: 'aut-partido-unico', n: 'Dictadura de partido único', y: 's. XX–', d: 'Un solo partido legal, fusionado con el Estado.', t: 'El partido representa a la nación entera.', c: 'Sin oposición legal no hay corrección de errores.', kw: ['partido único', 'prohibir partidos', 'ilegalizar la oposición'], risk: 3, why: 'La dictadura de partido único suprime el mecanismo que permite a una sociedad corregirse: cuando nadie puede señalar el error sin ser encarcelado, los errores escalan sin freno. El Gran Salto Adelante chino es el caso de manual —los cuadros locales inflaron las cifras de cosecha porque informar de la verdad era peligroso, y la hambruna resultante mató a entre 15 y 45 millones de personas.' },
        { id: 'aut-estado-policial', n: 'Estado policial', y: 's. XX–', d: 'Vigilancia masiva, delación e impunidad de las fuerzas de seguridad.', t: 'Seguridad total mediante control total.', c: 'La Stasi llegó a un informante por cada 6-7 ciudadanos.', kw: ['vigilancia masiva', 'policía política', 'delación', 'control total'], risk: 3, why: 'El estado policial destruye la confianza social como método de gobierno: la Stasi mantenía expedientes sobre un tercio de la población de la RDA y una red de informantes que llegó a incluir a vecinos, colegas y familiares directos. El efecto documentado no fue seguridad, sino una sociedad en la que hablar con sinceridad con cualquiera —incluida la propia pareja— era un riesgo calculado.' },
        { id: 'aut-autocracia', n: 'Autocracia', y: 'general', d: 'Categoría general: el poder reside en una persona o núcleo sin control externo.', t: 'Concentración total de la decisión.', c: 'Ningún mecanismo de corrección ni de sucesión pacífica.', kw: ['autocracia', 'poder sin control'], risk: 2 }
      ]
    },
    /* ---------------------------------------------------------------- 11 */
    {
      id: 'extremismos', n: 'Extremismos contemporáneos', code: 'EXT',
      blurb: 'Doctrinas que hoy justifican violencia, exclusión o exterminio. Zona de pin garantizado.',
      items: [
        { id: 'ext-supremacismo', n: 'Supremacismo racial', y: 's. XIX–', d: 'Jerarquía de valor humano según la raza.', t: 'Unos grupos humanos valen más que otros.', c: 'Científicamente falso: no existen razas humanas biológicas discretas.', kw: ['raza superior', 'supremacía blanca', 'jerarquía racial', 'razas inferiores'], risk: 3, why: 'El supremacismo racial parte de una premisa empíricamente falsa —la genética de poblaciones muestra más variación dentro de cualquier "raza" que entre ellas, y no existen fronteras biológicas discretas entre grupos humanos— y termina en esclavitud, segregación, linchamientos y genocidio. Es a la vez el error científico más refutado y la doctrina con más muertos a su cargo en la historia moderna.' },
        { id: 'ext-etnonacionalismo', n: 'Etnonacionalismo extremo', y: 's. XX–', d: 'Estado étnicamente homogéneo como objetivo político.', t: 'Un territorio, una etnia.', c: 'La homogeneidad solo se logra mediante expulsión o exterminio.', kw: ['limpieza étnica', 'estado étnicamente puro', 'expulsar a los que no son de aquí', 'remigración'], risk: 3, why: 'Ningún territorio del mundo es étnicamente homogéneo por naturaleza, así que la homogeneidad solo puede fabricarse: deportando o matando. Srebrenica (8.372 hombres y niños asesinados en julio de 1995) es lo que significa "un territorio, una etnia" en la práctica, y ocurrió en Europa, hace menos de treinta años, mientras había cámaras.' },
        { id: 'ext-teocracia', n: 'Teocracia extremista', y: 'varios', d: 'Interpretación literalista impuesta por la fuerza sobre toda la población.', t: 'La ley divina anula la ley civil y la conciencia individual.', c: 'Ejecuciones por apostasía, blasfemia u orientación sexual; exclusión de mujeres.', kw: ['ley divina obligatoria', 'castigar la apostasía', 'califato', 'pena por blasfemia'], risk: 3, why: 'Cuando una lectura religiosa se impone con el aparato del Estado, la disidencia se vuelve delito capital: bajo el ISIS hubo esclavización sistemática de mujeres yazidíes y ejecuciones públicas por apostasía; bajo el régimen talibán las mujeres perdieron el acceso a la educación secundaria y al trabajo. La víctima principal de estos regímenes es casi siempre la población creyente que vive bajo ellos.' },
        { id: 'ext-polpotismo', n: 'Polpotismo', y: '1975–1979', d: 'Jemeres Rojos: vaciado de ciudades, "año cero" y exterminio de las clases educadas.', t: 'Refundar la sociedad desde cero por la fuerza.', c: 'Entre 1,5 y 2 millones de muertos: un cuarto de la población camboyana.', kw: ['año cero', 'jemeres rojos', 'vaciar las ciudades', 'eliminar a los intelectuales'], risk: 3, why: 'Los Jemeres Rojos vaciaron Phnom Penh en 72 horas, abolieron el dinero, la escuela y la medicina moderna, y asesinaron a entre 1,5 y 2 millones de personas —cerca de un cuarto del país— por ser urbanas, alfabetizadas, budistas, de minoría étnica o simplemente por llevar gafas. Es la demostración más brutal de a dónde llega la idea de refundar una sociedad "desde cero".' },
        { id: 'ext-terrorismo', n: 'Terrorismo político', y: 'varios', d: 'Violencia contra población civil como método de presión política.', t: 'El fin justifica atacar a inocentes.', c: 'Fracasa en sus objetivos declarados y refuerza la represión que denuncia.', kw: ['atentado', 'violencia política', 'matar por la causa'], risk: 3, why: 'Además del daño directo, el terrorismo es estratégicamente contraproducente: los estudios comparados de campañas violentas frente a campañas de resistencia civil muestran que las no violentas tienen aproximadamente el doble de probabilidad de alcanzar sus objetivos. El atentado casi siempre entrega al Estado la legitimidad para la represión que el propio grupo denunciaba.' },
        { id: 'ext-negacionismo', n: 'Negacionismo histórico', y: '1950–', d: 'Negar o minimizar genocidios documentados.', t: 'La evidencia histórica es una fabricación.', c: 'Delito en varios países europeos; refutado por archivos, forense y testimonios.', kw: ['no hubo holocausto', 'exageran las cifras', 'invento histórico'], risk: 3, why: 'El negacionismo no es una hipótesis histórica alternativa: es una técnica de rehabilitación política. La Shoah está documentada por los propios archivos alemanes, la contabilidad de los campos, la evidencia forense de los emplazamientos, los testimonios de perpetradores en Núremberg y las cifras demográficas censales. Negarla no cuestiona un dato: prepara el terreno para repetir el hecho.' },
        { id: 'ext-aceleracionismo', n: 'Aceleracionismo violento', y: '2010–', d: 'Provocar el colapso social mediante atentados para forzar una guerra civil.', t: 'Cuanto peor, mejor.', c: 'Doctrina explícita de atentados de extrema derecha recientes.', kw: ['acelerar el colapso', 'guerra civil', 'cuanto peor mejor'], risk: 3, why: 'El aceleracionismo es hoy la doctrina operativa citada en manifiestos de atentados con víctimas reales (Christchurch 2019, 51 muertos; El Paso 2019, 23 muertos). Su premisa —que el colapso produce el orden deseado— no tiene ningún respaldo histórico: los colapsos estatales documentados (Somalia, Libia, Siria) producen señores de la guerra, hambre y desplazamiento masivo, no la sociedad soñada por nadie.' },
        { id: 'ext-eugenesia', n: 'Eugenesia coercitiva', y: '1900–1970', d: 'Control estatal de la reproducción para "mejorar" la población.', t: 'La calidad genética del pueblo como asunto de Estado.', c: 'Esterilizaciones forzosas masivas en EE. UU., Suecia, Japón y la Alemania nazi.', kw: ['esterilización forzosa', 'mejorar la raza', 'higiene racial', 'no deberían reproducirse'], risk: 3, why: 'La eugenesia coercitiva esterilizó por la fuerza a más de 60.000 personas en Estados Unidos y a decenas de miles en Suecia y Japón, y desembocó en el programa nazi Aktion T4, que asesinó a unas 200.000 personas con discapacidad. Su base científica era falsa —los rasgos que pretendía eliminar son poligénicos, ambientales o simplemente inventados ("debilidad moral")— y sus víctimas fueron sistemáticamente pobres, racializadas o discapacitadas.' }
      ]
    },
    /* ---------------------------------------------------------------- 12 */
    {
      id: 'feminismos', n: 'Feminismos', code: 'FEM',
      blurb: 'Corrientes sobre la igualdad de género y la crítica al patriarcado.',
      items: [
        { id: 'fem-liberal', n: 'Feminismo liberal', y: '1792–', d: 'Wollstonecraft, Friedan: igualdad legal y acceso a las mismas oportunidades.', t: 'Mismos derechos, mismas puertas abiertas.', c: 'No toca las estructuras económicas que generan la desigualdad.', kw: ['igualdad legal', 'techo de cristal', 'paridad'] },
        { id: 'fem-radical', n: 'Feminismo radical', y: '1960–', d: 'El patriarcado como sistema de dominación anterior a la clase.', t: 'Lo personal es político.', c: 'Divisiones internas profundas sobre sexo, género y trabajo sexual.', kw: ['patriarcado', 'lo personal es político', 'feminismo radical'] },
        { id: 'fem-socialista', n: 'Feminismo socialista', y: '1900–', d: 'Cruce de clase y género; trabajo de cuidados como base económica invisible.', t: 'Sin cambio económico no hay emancipación.', c: 'Tensión histórica con partidos de izquierda.', kw: ['trabajo de cuidados', 'clase y género', 'feminismo socialista'] },
        { id: 'fem-interseccional', n: 'Feminismo interseccional', y: '1989–', d: 'Crenshaw: las opresiones se cruzan y producen experiencias específicas.', t: 'No hay una sola mujer universal.', c: 'Complejidad que dificulta agendas unificadas.', kw: ['interseccionalidad', 'raza clase y género'] },
        { id: 'fem-negro', n: 'Feminismo negro', y: '1970–', d: 'hooks, Colectivo Combahee: género inseparable de racismo y clase.', t: 'La experiencia de las mujeres negras como punto de partida.', c: 'Marginado dentro del feminismo mayoritario.', kw: ['feminismo negro', 'combahee', 'bell hooks'] },
        { id: 'fem-ecofeminismo', n: 'Ecofeminismo', y: '1974–', d: 'Vincula explotación de la naturaleza y explotación de las mujeres.', t: 'La misma lógica somete cuerpos y territorios.', c: 'Criticado por esencialismo en algunas versiones.', kw: ['ecofeminismo', 'cuerpos y territorios'] },
        { id: 'fem-diferencia', n: 'Feminismo de la diferencia', y: '1970–', d: 'Irigaray: valorar lo femenino en lugar de asimilarlo al modelo masculino.', t: 'Igualdad no significa identidad.', c: 'Riesgo de reforzar estereotipos.', kw: ['diferencia sexual', 'valor de lo femenino'] },
        { id: 'fem-institucional', n: 'Feminismo institucional', y: '1975–', d: 'Políticas públicas de igualdad, cuotas y organismos específicos.', t: 'Transformar desde dentro del Estado.', c: 'Acusado de burocratizar el movimiento.', kw: ['políticas de igualdad', 'cuotas', 'ministerio de igualdad'] },
        { id: 'fem-transfeminismo', n: 'Transfeminismo', y: '1990–', d: 'Incluye identidades trans y no binarias en el sujeto del feminismo.', t: 'El género no se reduce al sexo asignado.', c: 'Punto de fractura abierto con corrientes radicales.', kw: ['transfeminismo', 'identidad de género', 'no binario'] },
        { id: 'fem-decolonial', n: 'Feminismo decolonial', y: '2000–', d: 'Lugones, Segato: el género tal como lo conocemos es también una imposición colonial.', t: 'Descolonizar también el feminismo.', c: 'Alta abstracción teórica.', kw: ['feminismo decolonial', 'colonialidad del género'] },
        { id: 'fem-antifeminismo', n: 'Antifeminismo reaccionario', y: 's. XX–', d: 'Movimientos que niegan la desigualdad de género y buscan revertir derechos.', t: 'La igualdad ya está lograda o ha ido demasiado lejos.', c: 'Contradicho por datos de brecha salarial, violencia y cuidados.', kw: ['ideología de género', 'feminazi', 'los hombres son las víctimas'], risk: 1 }
      ]
    },
    /* ---------------------------------------------------------------- 13 */
    {
      id: 'ecologismo', n: 'Ecologismo', code: 'ECO',
      blurb: 'La biosfera como límite y como sujeto político.',
      items: [
        { id: 'eco-conservacionismo', n: 'Conservacionismo', y: '1900–', d: 'Proteger espacios y especies mediante reservas y regulación.', t: 'Salvar lo que queda.', c: 'A veces excluyó a comunidades indígenas de sus territorios.', kw: ['parques naturales', 'proteger especies', 'reservas'] },
        { id: 'eco-verde-politico', n: 'Ecologismo político', y: '1970–', d: 'Partidos verdes: ecología, paz, feminismo y democracia de base.', t: 'La crisis ecológica es una crisis de modelo.', c: 'Tensión permanente entre gobernar y no diluirse.', kw: ['partido verde', 'transición ecológica', 'cambio climático'] },
        { id: 'eco-decrecimiento', n: 'Decrecimiento', y: '2000–', d: 'Reducción planificada de producción y consumo en los países ricos.', t: 'No hay crecimiento infinito en un planeta finito.', c: 'Debate abierto sobre empleo y sistemas de pensiones.', kw: ['decrecimiento', 'límites del planeta', 'consumir menos'] },
        { id: 'eco-modernismo', n: 'Ecomodernismo', y: '2015–', d: 'Desacoplar bienestar y emisiones mediante tecnología, nuclear y densificación.', t: 'Más tecnología, no menos.', c: 'Optimismo tecnológico cuestionado por los plazos reales.', kw: ['ecomodernismo', 'nuclear', 'desacoplamiento', 'tecnología limpia'] },
        { id: 'eco-profunda', n: 'Ecología profunda', y: '1973–', d: 'Naess: la naturaleza tiene valor intrínseco, no solo utilidad humana.', t: 'La biosfera no está a nuestro servicio.', c: 'Versiones misantrópicas problemáticas.', kw: ['ecología profunda', 'valor intrínseco de la naturaleza'] },
        { id: 'eco-justicia', n: 'Justicia ambiental', y: '1980–', d: 'El daño ecológico se reparte según clase, raza y territorio.', t: 'Quien menos contamina, más sufre.', c: 'Difícil de traducir en instrumentos internacionales.', kw: ['justicia climática', 'racismo ambiental', 'sur global'] },
        { id: 'eco-animalismo', n: 'Animalismo', y: '1975–', d: 'Singer, Regan: los animales tienen intereses moralmente relevantes.', t: 'El sufrimiento cuenta, sea de quien sea.', c: 'Choca con la economía ganadera y con tradiciones locales.', kw: ['derechos animales', 'antiespecismo', 'veganismo político'] },
        { id: 'eco-negacionismo', n: 'Negacionismo climático', y: '1990–', d: 'Niega la existencia o la causa humana del calentamiento global.', t: 'Los datos climáticos son alarmismo o fraude.', c: 'Contradicho por más del 97 % de la literatura científica revisada.', kw: ['el clima siempre', 'clima siempre ha cambiado', 'estafa climatica', 'timo del clima', 'no hay calentamiento', 'alarmismo climatico', 'el clima es una estafa'], risk: 1 }
      ]
    },
    /* ---------------------------------------------------------------- 14 */
    {
      id: 'monarquismo', n: 'Monarquismo', code: 'MON',
      blurb: 'La jefatura del Estado hereditaria como principio de continuidad.',
      items: [
        { id: 'mon-constitucional', n: 'Monarquía constitucional', y: 's. XIX–', d: 'El rey reina pero no gobierna; el poder reside en el parlamento.', t: 'Símbolo neutral por encima de la política.', c: 'Legitimidad hereditaria en un sistema que se dice igualitario.', kw: ['monarquía parlamentaria', 'el rey reina no gobierna'] },
        { id: 'mon-absoluta', n: 'Monarquía absoluta', y: 's. XVI–XVIII', d: 'Poder ilimitado del monarca sin control institucional.', t: 'El soberano es la fuente de toda ley.', c: 'Arbitrariedad estructural.', kw: ['monarquía absoluta', 'poder ilimitado del rey'], risk: 2 },
        { id: 'mon-legitimismo', n: 'Legitimismo', y: 's. XIX–', d: 'Solo la dinastía legítima puede reinar; rechazo de los cambios revolucionarios.', t: 'La legitimidad es dinástica, no popular.', c: 'Ha alimentado guerras civiles dinásticas.', kw: ['legitimismo', 'carlismo', 'dinastía legítima'], risk: 1 },
        { id: 'mon-imperial', n: 'Monarquía imperial', y: 'antiguo–s. XX', d: 'Corona que gobierna un conjunto multinacional de territorios.', t: 'Unidad supranacional bajo una casa reinante.', c: 'Sometimiento de pueblos sin consentimiento.', kw: ['imperio', 'corona imperial'], risk: 2 },
        { id: 'mon-electiva', n: 'Monarquía electiva', y: 'medieval–', d: 'El monarca es elegido por un cuerpo de electores.', t: 'Corona sin herencia automática.', c: 'Interregnos y luchas facciosas.', kw: ['monarquía electiva'] },
        { id: 'mon-jacobitismo', n: 'Restauracionismo', y: 's. XVIII–', d: 'Restaurar una casa reinante depuesta.', t: 'Reparar una ruptura histórica ilegítima.', c: 'Casi siempre residual y nostálgico.', kw: ['restaurar la monarquía', 'restauración dinástica'] }
      ]
    },
    /* ---------------------------------------------------------------- 15 */
    {
      id: 'religiosas', n: 'Ideologías religiosas y políticas', code: 'REL',
      blurb: 'Relaciones entre fe y poder político, del laicismo a la teocracia.',
      items: [
        { id: 'rel-laicismo', n: 'Laicismo', y: '1789–', d: 'Separación estricta entre instituciones religiosas y Estado.', t: 'La ley es de todos, no de una fe.', c: 'Debate sobre si limita la libertad religiosa en el espacio público.', kw: ['laicismo', 'estado laico', 'separación iglesia estado'] },
        { id: 'rel-teologia-liberacion', n: 'Teología de la liberación', y: '1968–', d: 'Cristianismo latinoamericano comprometido con los oprimidos.', t: 'Opción preferencial por los pobres.', c: 'Reprimida por Roma y por dictaduras militares.', kw: ['teología de la liberación', 'iglesia de los pobres'] },
        { id: 'rel-democracia-cristiana', n: 'Humanismo cristiano', y: 's. XX–', d: 'Maritain: dignidad de la persona como base de la democracia.', t: 'Personalismo cristiano y pluralismo.', c: 'Difuminado en el centro político.', kw: ['humanismo cristiano', 'personalismo'] },
        { id: 'rel-islamismo-politico', n: 'Islamismo político', y: '1928–', d: 'Corrientes que buscan organizar el Estado según principios islámicos, desde partidos electorales hasta grupos armados.', t: 'El islam como marco de la vida pública.', c: 'Espectro amplísimo: no equiparar participación electoral con yihadismo.', kw: ['islamismo político', 'partido islámico', 'sharía en el estado'], risk: 1 },
        { id: 'rel-sionismo', n: 'Sionismo', y: '1897–', d: 'Movimiento por un Estado nacional judío; incluye vertientes laborales, liberales y religiosas.', t: 'Autodeterminación nacional judía.', c: 'Debate central sobre derechos de la población palestina.', kw: ['sionismo', 'estado judío'] },
        { id: 'rel-hindutva', n: 'Hindutva', y: '1923–', d: 'Nacionalismo hindú: India definida como nación hindú.', t: 'Identidad nacional y religiosa coincidentes.', c: 'Asociado a violencia comunal contra minorías musulmanas.', kw: ['hindutva', 'nacionalismo hindú'], risk: 2 },
        { id: 'rel-fundamentalismo', n: 'Fundamentalismo religioso', y: '1900–', d: 'Lectura literal e innegociable del texto sagrado aplicada a la ley.', t: 'La revelación no admite interpretación ni contexto.', c: 'Anula la libertad de conciencia; presente en todas las confesiones.', kw: ['literalismo', 'fundamentalismo', 'sin interpretación'], risk: 2 },
        { id: 'rel-clericalismo', n: 'Clericalismo', y: 's. XIX–', d: 'Influencia institucional del clero sobre el poder civil.', t: 'La jerarquía religiosa debe orientar la política.', c: 'Poder no electo sobre asuntos públicos.', kw: ['clericalismo', 'poder del clero'], risk: 1 },
        { id: 'rel-ateismo-estado', n: 'Ateísmo de Estado', y: '1917–', d: 'Persecución oficial de la religión por el aparato estatal.', t: 'Erradicar la fe como programa político.', c: 'Iglesias demolidas, clero ejecutado: violación de la libertad de conciencia.', kw: ['ateísmo de estado', 'prohibir la religión', 'perseguir creyentes'], risk: 2 }
      ]
    },
    /* ---------------------------------------------------------------- 16 */
    {
      id: 'economicas', n: 'Doctrinas económicas', code: 'ECN',
      blurb: 'Escuelas sobre cómo se produce y se reparte la riqueza.',
      items: [
        { id: 'ecn-keynesianismo', n: 'Keynesianismo', y: '1936–', d: 'Gasto público para sostener la demanda en las recesiones.', t: 'El mercado no se autocorrige a corto plazo.', c: 'Riesgo de inflación y de déficit persistente.', kw: ['estímulo fiscal', 'gasto público', 'demanda agregada', 'obra pública'] },
        { id: 'ecn-monetarismo', n: 'Monetarismo', y: '1960–', d: 'Friedman: controlar la masa monetaria es controlar la inflación.', t: '"La inflación es siempre un fenómeno monetario".', c: 'La relación dinero-precios resultó menos estable de lo previsto.', kw: ['masa monetaria', 'controlar la inflación', 'banco central independiente'] },
        { id: 'ecn-austriaca', n: 'Escuela austriaca', y: '1871–', d: 'Mises, Hayek: el cálculo económico centralizado es imposible.', t: 'Los precios transmiten información dispersa.', c: 'Rechaza la contrastación empírica formal.', kw: ['escuela austriaca', 'cálculo económico', 'ciclo austriaco', 'hayek'] },
        { id: 'ecn-mercantilismo', n: 'Mercantilismo', y: 's. XVI–XVIII', d: 'Acumular metales y superávit comercial mediante control estatal.', t: 'El comercio es un juego de suma cero.', c: 'Refutado por la teoría de la ventaja comparativa.', kw: ['balanza comercial', 'acumular oro', 'exportar más que importar'] },
        { id: 'ecn-desarrollismo', n: 'Desarrollismo', y: '1950–1980', d: 'Prebisch, CEPAL: industrialización dirigida por el Estado.', t: 'La periferia no se desarrolla exportando materias primas.', c: 'Industrias protegidas poco competitivas y deuda externa.', kw: ['sustitución de importaciones', 'industrialización', 'cepal'] },
        { id: 'ecn-georgismo', n: 'Georgismo', y: '1879–', d: 'Impuesto único sobre el valor del suelo.', t: 'Gravar la renta no ganada, no el trabajo.', c: 'Difícil de aplicar como única fuente fiscal.', kw: ['impuesto al suelo', 'renta de la tierra', 'georgismo'] },
        { id: 'ecn-distributismo', n: 'Distributismo', y: '1900–', d: 'Chesterton, Belloc: repartir la propiedad, no abolirla.', t: 'Muchos pequeños propietarios en lugar de trusts o Estado.', c: 'Difícil competir con economías de escala.', kw: ['distributismo', 'pequeña propiedad', 'ni trust ni estado'] },
        { id: 'ecn-mmt', n: 'Teoría Monetaria Moderna', y: '1990–', d: 'Un Estado con moneda propia no quiebra en su divisa; el límite es la inflación.', t: 'Primero se gasta, después se recauda.', c: 'Muy discutida; no aplicable a países sin soberanía monetaria.', kw: ['mmt', 'emitir moneda', 'déficit no importa'] },
        { id: 'ecn-institucionalismo', n: 'Institucionalismo', y: '1900–', d: 'North, Acemoglu: las instituciones explican por qué unos países prosperan.', t: 'Las reglas importan más que los recursos.', c: 'Riesgo de circularidad explicativa.', kw: ['instituciones inclusivas', 'reglas del juego', 'por qué fracasan los países'] },
        { id: 'ecn-conductual', n: 'Economía conductual', y: '1979–', d: 'Kahneman, Thaler: decisiones humanas sistemáticamente sesgadas.', t: 'El agente racional no existe.', c: 'Crisis de replicación en parte de sus resultados.', kw: ['sesgos cognitivos', 'nudge', 'economía conductual'] },
        { id: 'ecn-rentabasica', n: 'Renta básica universal', y: '1980–', d: 'Transferencia incondicional a toda la población.', t: 'Suelo de seguridad económica sin condiciones.', c: 'Coste fiscal y efectos sobre el empleo aún en discusión.', kw: ['renta básica', 'ingreso universal', 'dinero incondicional'] }
      ]
    },
    /* ---------------------------------------------------------------- 17 */
    {
      id: 'populismos', n: 'Populismos', code: 'POP',
      blurb: 'Lógica política que divide la sociedad entre "pueblo puro" y "élite corrupta".',
      items: [
        { id: 'pop-izquierda', n: 'Populismo de izquierda', y: '1990–', d: 'Pueblo frente a oligarquía económica y financiera.', t: 'Recuperar la soberanía popular sobre la economía.', c: 'Personalismo y debilitamiento de contrapesos.', kw: ['la casta', 'el pueblo contra la oligarquía', 'los de abajo'], risk: 1 },
        { id: 'pop-derecha', n: 'Populismo de derecha', y: '1990–', d: 'Pueblo nativo frente a élites globalistas e inmigración.', t: 'Devolver el país a su gente.', c: 'Deriva nativista y erosión de instituciones.', kw: ['élite globalista', 'devolver el país', 'nos invaden', 'políticos corruptos y extranjeros'], risk: 2 },
        { id: 'pop-agrario', n: 'Populismo agrario', y: '1890–', d: 'Pequeños productores frente a bancos e intermediarios.', t: 'Quien trabaja la tierra frente a quien especula.', c: 'Absorbido por otras corrientes.', kw: ['agricultores contra bancos', 'populismo rural'] },
        { id: 'pop-tecnocratico', n: 'Antipolítica tecnocrática', y: '2000–', d: 'Sustituir la política por gestión "neutral" de expertos.', t: 'Los problemas son técnicos, no ideológicos.', c: 'Retira decisiones fundamentales del control democrático.', kw: ['que gobiernen los técnicos', 'la política sobra', 'gestión neutral'], risk: 1 },
        { id: 'pop-plebiscitario', n: 'Populismo plebiscitario', y: 's. XX–', d: 'Relación directa líder-pueblo sin mediación institucional.', t: 'El líder encarna la voluntad popular.', c: 'Los cuerpos intermedios pasan a ser obstáculos a eliminar.', kw: ['el líder y el pueblo', 'sin intermediarios', 'los jueces estorban'], risk: 2 },
        { id: 'pop-conspiracionismo', n: 'Conspiracionismo político', y: 's. XX–', d: 'Explica la política mediante planes ocultos de grupos secretos.', t: 'Todo obedece a un plan deliberado.', c: 'Muchas variantes reciclan estructuras antisemitas clásicas.', kw: ['plan oculto', 'gran reseteo', 'élites secretas', 'nos controlan', 'agenda 2030 mundial'], risk: 2 }
      ]
    },
    /* ---------------------------------------------------------------- 18 */
    {
      id: 'identitarias', n: 'Políticas identitarias', code: 'IDE',
      blurb: 'La identidad de grupo como base de la reivindicación política.',
      items: [
        { id: 'ide-multiculturalismo', n: 'Multiculturalismo', y: '1970–', d: 'Reconocimiento de derechos culturales diferenciados dentro de un Estado.', t: 'La igualdad exige reconocer la diferencia.', c: 'Riesgo de fragmentación y de blindar prácticas iliberales.', kw: ['multiculturalismo', 'derechos culturales', 'diversidad'] },
        { id: 'ide-interculturalidad', n: 'Interculturalidad', y: '1990–', d: 'Intercambio activo entre culturas, no coexistencia paralela.', t: 'Convivir es mezclarse, no yuxtaponerse.', c: 'Difícil de traducir en política pública medible.', kw: ['interculturalidad', 'convivencia', 'diálogo cultural'] },
        { id: 'ide-indigenismo', n: 'Indigenismo', y: '1920–', d: 'Derechos, territorio y autogobierno de los pueblos originarios.', t: 'Reparación histórica y plurinacionalidad.', c: 'Tensión con el Estado unitario y con industrias extractivas.', kw: ['pueblos originarios', 'plurinacionalidad', 'derechos indígenas'] },
        { id: 'ide-lgtbi', n: 'Movimiento LGTBI+', y: '1969–', d: 'Igualdad legal y social con independencia de orientación e identidad.', t: 'Derechos plenos sin excepción.', c: 'Debates internos sobre estrategia e institucionalización.', kw: ['derechos lgtbi', 'matrimonio igualitario', 'diversidad sexual'] },
        { id: 'ide-panafricanismo', n: 'Panafricanismo', y: '1900–', d: 'Unidad política y cultural de los pueblos africanos y de la diáspora.', t: 'Solidaridad continental frente al colonialismo.', c: 'Nunca se materializó institucionalmente.', kw: ['panafricanismo', 'unidad africana', 'diáspora'] },
        { id: 'ide-identitarismo', n: 'Identitarismo etnodiferencialista', y: '1980–', d: 'Nouvelle Droite: "derecho a la diferencia" usado para justificar la separación étnica.', t: 'Cada pueblo en su sitio, sin mezcla.', c: 'Segregacionismo con vocabulario antirracista.', kw: ['derecho a la diferencia', 'etnopluralismo', 'gran reemplazo', 'remigración'], risk: 3, why: 'El identitarismo etnodiferencialista es segregación reescrita con vocabulario de respeto: sustituye "raza superior" por "cada pueblo en su lugar" y llega a la misma conclusión operativa, la expulsión. Su teoría del "gran reemplazo" es demográficamente falsa —los cambios poblacionales europeos se explican por natalidad y migración económica, no por ningún plan— y ha sido citada explícitamente en los manifiestos de los atentados de Christchurch (51 muertos), El Paso (23) y Buffalo (10).' },
        { id: 'ide-asimilacionismo', n: 'Asimilacionismo', y: 's. XIX–', d: 'La minoría debe adoptar la cultura mayoritaria para ser aceptada.', t: 'Una sola cultura pública común.', c: 'Ha implicado prohibición de lenguas y separación de familias.', kw: ['asimilación', 'que se adapten', 'una sola cultura'], risk: 1 }
      ]
    },
    /* ---------------------------------------------------------------- 19 */
    {
      id: 'tecnologicas', n: 'Ideologías tecnológicas', code: 'TEC',
      blurb: 'Visiones políticas organizadas en torno a la técnica y su futuro.',
      items: [
        { id: 'tec-tecnocracia', n: 'Tecnocracia', y: '1930–', d: 'Gobierno de expertos e ingenieros según criterios técnicos.', t: 'Decidir con datos, no con votos.', c: 'Los fines políticos no se deducen de los datos.', kw: ['gobierno de expertos', 'tecnocracia', 'decisiones técnicas'], risk: 1 },
        { id: 'tec-transhumanismo', n: 'Transhumanismo', y: '1990–', d: 'Mejora tecnológica de las capacidades humanas, incluida la longevidad.', t: 'La condición humana es modificable.', c: 'Riesgo de desigualdad biológica entre quien accede y quien no.', kw: ['transhumanismo', 'mejora humana', 'longevidad', 'ciborg'] },
        { id: 'tec-aceleracionismo', n: 'Aceleracionismo tecnológico', y: '2010–', d: 'Acelerar el desarrollo técnico para superar el orden actual.', t: 'No frenar: atravesar.', c: 'Sus variantes de derecha derivan en desprecio por la democracia.', kw: ['acelerar la tecnología', 'e/acc', 'sin frenos'], risk: 1 },
        { id: 'tec-ciberlibertarismo', n: 'Ciberlibertarismo', y: '1990–', d: 'Internet como espacio soberano fuera del alcance de los Estados.', t: '"Los gobiernos no tienen soberanía aquí".', c: 'El resultado fue el poder de las plataformas, no la libertad.', kw: ['internet libre', 'ciberespacio soberano', 'sin regulación digital'] },
        { id: 'tec-decrecimiento-digital', n: 'Tecnocrítica', y: '1960–', d: 'Ellul, Illich, Mumford: la técnica reorganiza la sociedad a su medida.', t: 'Toda tecnología incorpora una política.', c: 'Poca propuesta práctica alternativa.', kw: ['crítica de la técnica', 'tecnología no es neutral'] },
        { id: 'tec-datos-publicos', n: 'Soberanía digital', y: '2010–', d: 'Control público sobre datos, infraestructura y algoritmos.', t: 'Los datos son infraestructura crítica.', c: 'Puede confundirse con censura o proteccionismo digital.', kw: ['soberanía digital', 'datos públicos', 'regular plataformas', 'algoritmos'] },
        { id: 'tec-vigilancia', n: 'Autoritarismo digital', y: '2010–', d: 'Reconocimiento facial, crédito social y censura algorítmica al servicio del control.', t: 'La tecnología permite un control social total.', c: 'Vigilancia de minorías y puntuación de conductas privadas.', kw: ['crédito social', 'reconocimiento facial masivo', 'censura algorítmica', 'vigilar a todos'], risk: 3, why: 'El autoritarismo digital hace lo que ninguna dictadura del siglo XX pudo: vigilancia total, permanente y barata. En Xinjiang se ha documentado reconocimiento facial dirigido por etnia, controles biométricos obligatorios y campos de internamiento con más de un millón de personas. La diferencia con la Stasi no es de intención sino de capacidad, y esa capacidad ya no requiere informantes: basta con la infraestructura.' }
      ]
    }
  ];

  /* ---- Índice plano + utilidades ------------------------------------ */
  var ALL = [];
  F.forEach(function (fam) {
    fam.items.forEach(function (it) {
      it.family = fam.id;
      it.familyName = fam.n;
      it.code = fam.code;
      it.risk = it.risk || 0;
      ALL.push(it);
    });
  });

  var BY_ID = {};
  ALL.forEach(function (i) { BY_ID[i.id] = i; });

  global.PS_IDEOLOGIES = {
    families: F,
    all: ALL,
    byId: function (id) { return BY_ID[id] || null; },
    pins: ALL.filter(function (i) { return i.risk === 3; }),
    total: ALL.length
  };
})(window);
